import { useState } from 'react';
import { Check, MessageSquare, Pencil, Search, Trash2, X } from 'lucide-react';
import type { Session } from '@/lib/api';
import { ScrollArea } from '@/components/ui/scroll-area';
import { cn } from '@/lib/utils';
import { useTranslation } from '@/i18n';

interface Props { sessions: Session[]; activeSessionId: string | null; busyId: string | null; onSelectSession: (id: string) => void; onRenameSession: (id: string, title: string) => Promise<void>; onDeleteSession: (id: string) => Promise<void> }
export function SessionDrawer({ sessions, activeSessionId, busyId, onSelectSession, onRenameSession, onDeleteSession }: Props) {
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<{ id: string; title: string } | null>(null);
  const { t } = useTranslation();
  // An empty title marks the session untitled (the auto-titler names it
  // after the first exchange); render the localized placeholder.
  const label = (session: Session) => session.title || t('errors.newSessionDefault');
  const filtered = query.trim() ? sessions.filter((session) => label(session).toLowerCase().includes(query.trim().toLowerCase())) : sessions;
  const save = async () => { if (!editing?.title.trim()) return; await onRenameSession(editing.id, editing.title.trim()); setEditing(null); };
  return <div className="flex h-full flex-col"><div className="border-b px-4 py-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('sessionDrawer.searchPlaceholder')} className="h-9 w-full rounded-lg border bg-card pl-9 pr-3 text-sm outline-none focus:border-primary"/></div></div><ScrollArea className="flex-1 px-3 pb-3">{filtered.length === 0 ? <div className="py-12 text-center text-sm text-muted-foreground"><MessageSquare className="mx-auto mb-2 h-8 w-8 opacity-40"/>{query ? t('sessionDrawer.noMatch') : t('sessionDrawer.empty')}</div> : <div className="space-y-1">{filtered.map((session) => <div key={session.id} onClick={() => editing?.id !== session.id && onSelectSession(session.id)} className={cn('group flex min-h-10 items-center gap-2 rounded-xl px-3 py-2 text-sm', activeSessionId === session.id ? 'bg-sidebar-accent' : 'hover:bg-sidebar-accent/50', busyId === session.id && 'opacity-60')}><MessageSquare className="h-3.5 w-3.5 shrink-0"/>{editing?.id === session.id ? <input autoFocus value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} onKeyDown={(event) => { if (event.key === 'Enter') void save(); if (event.key === 'Escape') setEditing(null); }} className="min-w-0 flex-1 rounded border bg-background px-2 py-1"/> : <span className={cn('flex-1 truncate', !session.title && 'text-muted-foreground')}>{label(session)}</span>}{editing?.id === session.id ? <><button onClick={(event) => { event.stopPropagation(); void save(); }} title={t('common.save')}><Check className="h-3.5 w-3.5"/></button><button onClick={(event) => { event.stopPropagation(); setEditing(null); }} title={t('common.cancel')}><X className="h-3.5 w-3.5"/></button></> : <><button onClick={(event) => { event.stopPropagation(); setEditing({ id: session.id, title: session.title }); }} className="opacity-0 group-hover:opacity-100" title={t('sessionDrawer.rename')}><Pencil className="h-3.5 w-3.5"/></button><button onClick={(event) => { event.stopPropagation(); if (window.confirm(t('sessionDrawer.confirmDelete', { title: label(session) }))) void onDeleteSession(session.id); }} className="opacity-0 group-hover:opacity-100" title={t('common.delete')}><Trash2 className="h-3.5 w-3.5 text-destructive"/></button></>}</div>)}</div>}</ScrollArea></div>;
}
