package assembly

import (
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var goIdentifierPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// GenerateBinder emits static constructor calls in lifecycle order. Runtime
// selection is impossible because every import and constructor is frozen into
// the compiled source.
func GenerateBinder(plan AssemblyPlan, packageName string) ([]byte, error) {
	if !goIdentifierPattern.MatchString(packageName) {
		return nil, fmt.Errorf("invalid generated package name %q", packageName)
	}
	modules := make(map[string]ResolvedModule, len(plan.Modules))
	for _, resolved := range plan.Modules {
		id := resolved.Descriptor.Module.ID
		if resolved.Binding.ImportPath == "" || resolved.Binding.Package == "" || resolved.Binding.Constructor == "" {
			return nil, fmt.Errorf("missing Go binding for %s", id)
		}
		if !goIdentifierPattern.MatchString(resolved.Binding.Package) || !goIdentifierPattern.MatchString(resolved.Binding.Constructor) {
			return nil, fmt.Errorf("invalid Go binding for %s", id)
		}
		if _, duplicate := modules[id]; duplicate {
			return nil, fmt.Errorf("duplicate AssemblyPlan module %s", id)
		}
		modules[id] = resolved
	}
	if len(plan.LifecycleOrder) != len(modules) {
		return nil, fmt.Errorf("lifecycle order has %d modules, want %d", len(plan.LifecycleOrder), len(modules))
	}
	seen := make(map[string]struct{}, len(modules))
	for _, id := range plan.LifecycleOrder {
		if _, exists := modules[id]; !exists {
			return nil, fmt.Errorf("lifecycle module %s is not in AssemblyPlan", id)
		}
		if _, duplicate := seen[id]; duplicate {
			return nil, fmt.Errorf("duplicate lifecycle module %s", id)
		}
		seen[id] = struct{}{}
	}

	imports := make([]ResolvedModule, 0, len(modules))
	for _, resolved := range modules {
		imports = append(imports, resolved)
	}
	sort.Slice(imports, func(i, j int) bool {
		if imports[i].Binding.ImportPath == imports[j].Binding.ImportPath {
			return imports[i].Binding.Package < imports[j].Binding.Package
		}
		return imports[i].Binding.ImportPath < imports[j].Binding.ImportPath
	})
	aliases := make(map[string]string, len(imports))
	usedAliases := make(map[string]struct{}, len(imports))
	pathAliases := make(map[string]string, len(imports))
	for _, resolved := range imports {
		if alias, exists := pathAliases[resolved.Binding.ImportPath]; exists {
			aliases[resolved.Descriptor.Module.ID] = alias
			continue
		}
		alias := resolved.Binding.Package
		base := alias
		for suffix := 2; ; suffix++ {
			if _, used := usedAliases[alias]; !used {
				break
			}
			alias = base + strconv.Itoa(suffix)
		}
		usedAliases[alias] = struct{}{}
		aliases[resolved.Descriptor.Module.ID] = alias
		pathAliases[resolved.Binding.ImportPath] = alias
	}

	var source strings.Builder
	source.WriteString("// Code generated by vivy-sdk. DO NOT EDIT.\n\npackage ")
	source.WriteString(packageName)
	source.WriteString("\n\nimport (\n\t\"context\"\n\t\"errors\"\n\n\t\"agent-vivy/sdk/module\"\n")
	paths := make([]string, 0, len(pathAliases))
	for path := range pathAliases {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&source, "\t%s %q\n", pathAliases[path], path)
	}
	source.WriteString(")\n\n")
	source.WriteString("type HostResolver interface {\n\tForModule(string) module.Host\n}\n\n")
	source.WriteString("type Owners struct {\n\towners []module.Instance\n}\n\n")
	source.WriteString("func Construct(ctx context.Context, hosts HostResolver) (*Owners, error) {\n\towners := make([]module.Instance, 0, ")
	source.WriteString(strconv.Itoa(len(plan.LifecycleOrder)))
	source.WriteString(")\n")
	for index, id := range plan.LifecycleOrder {
		resolved := modules[id]
		alias := aliases[id]
		fmt.Fprintf(&source, "\towner%d, err := %s.%s().Construct(ctx, hosts.ForModule(%q))\n", index, alias, resolved.Binding.Constructor, id)
		source.WriteString("\tif err != nil {\n\t\treturn nil, errors.Join(err, closeOwners(ctx, owners))\n\t}\n")
		fmt.Fprintf(&source, "\towners = append(owners, owner%d)\n", index)
	}
	source.WriteString("\treturn &Owners{owners: owners}, nil\n}\n\n")
	source.WriteString("func (assembly *Owners) Start(ctx context.Context) error {\n\tfor index, owner := range assembly.owners {\n\t\tif err := owner.Start(ctx); err != nil {\n\t\t\treturn errors.Join(err, rollbackStart(ctx, assembly.owners, index+1))\n\t\t}\n\t\tif err := owner.Ready(ctx); err != nil {\n\t\t\treturn errors.Join(err, rollbackStart(ctx, assembly.owners, index+1))\n\t\t}\n\t}\n\treturn nil\n}\n\n")
	source.WriteString("func (assembly *Owners) Close(ctx context.Context) error {\n\treturn stopAndCloseOwners(ctx, assembly.owners)\n}\n\n")
	source.WriteString("func rollbackStart(ctx context.Context, owners []module.Instance, started int) error {\n\tvar failures []error\n\tfor index := started - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Stop(ctx))\n\t}\n\tfor index := len(owners) - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Close(ctx))\n\t}\n\treturn errors.Join(failures...)\n}\n\n")
	source.WriteString("func stopAndCloseOwners(ctx context.Context, owners []module.Instance) error {\n\tvar failures []error\n\tfor index := len(owners) - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Stop(ctx), owners[index].Close(ctx))\n\t}\n\treturn errors.Join(failures...)\n}\n\n")
	source.WriteString("func closeOwners(ctx context.Context, owners []module.Instance) error {\n\tvar failures []error\n\tfor index := len(owners) - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Close(ctx))\n\t}\n\treturn errors.Join(failures...)\n}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated binder: %w", err)
	}
	return formatted, nil
}
