package assembly

import (
	"bytes"
	"strings"
	"testing"
)

func TestGenerateBinderIsStableAndUsesTypedConstructors(t *testing.T) {
	plan := AssemblyPlan{
		Modules: []ResolvedModule{
			{
				Descriptor: testDescriptor("fixture/search"),
				Trust:      TrustT2,
				Binding: GoBinding{
					ImportPath:  "example.com/acme/search",
					Package:     "search",
					Constructor: "NewModule",
				},
			},
			{
				Descriptor: testDescriptor("fixture/clock"),
				Trust:      TrustT1,
				Binding: GoBinding{
					ImportPath:  "agent-vivy/internal/modules/clock",
					Package:     "clock",
					Constructor: "New",
				},
			},
		},
		LifecycleOrder: []string{"fixture/clock", "fixture/search"},
	}

	first, err := GenerateBinder(plan, "assembly")
	if err != nil {
		t.Fatalf("GenerateBinder() error = %v", err)
	}
	second, err := GenerateBinder(plan, "assembly")
	if err != nil {
		t.Fatalf("GenerateBinder() second error = %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("GenerateBinder() is not byte stable")
	}
	source := string(first)
	for _, required := range []string{
		"// Code generated by vivy-sdk. DO NOT EDIT.",
		`clock "agent-vivy/internal/modules/clock"`,
		`search "example.com/acme/search"`,
		"clock.New().Construct(ctx, hosts.ForModule(\"fixture/clock\"))",
		"search.NewModule().Construct(ctx, hosts.ForModule(\"fixture/search\"))",
		"for index := len(owners) - 1; index >= 0; index--",
	} {
		if !strings.Contains(source, required) {
			t.Fatalf("generated binder missing %q:\n%s", required, source)
		}
	}
	if strings.Contains(source, "reflect.") || strings.Contains(source, "[]any") {
		t.Fatalf("generated binder uses an untyped registry:\n%s", source)
	}
}

func TestGenerateBinderRejectsMissingBindingAndLifecycleNode(t *testing.T) {
	tests := []struct {
		name      string
		plan      AssemblyPlan
		wantError string
	}{
		{
			name: "missing build binding",
			plan: AssemblyPlan{
				Modules:        []ResolvedModule{{Descriptor: testDescriptor("fixture/search"), Trust: TrustT2}},
				LifecycleOrder: []string{"fixture/search"},
			},
			wantError: "missing Go binding for fixture/search",
		},
		{
			name: "lifecycle references absent module",
			plan: AssemblyPlan{
				Modules: []ResolvedModule{{
					Descriptor: testDescriptor("fixture/search"),
					Trust:      TrustT2,
					Binding:    GoBinding{ImportPath: "example.com/acme/search", Package: "search", Constructor: "New"},
				}},
				LifecycleOrder: []string{"fixture/missing"},
			},
			wantError: "lifecycle module fixture/missing is not in AssemblyPlan",
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := GenerateBinder(test.plan, "assembly")
			if err == nil || !strings.Contains(err.Error(), test.wantError) {
				t.Fatalf("GenerateBinder() error = %v, want substring %q", err, test.wantError)
			}
		})
	}
}
