package assembly

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// GenerateRuntimeAssembly emits the application-facing Provider inventory
// from the same compiled plan used for the lifecycle binder and manifest.
func GenerateRuntimeAssembly(plan AssemblyPlan, packageName string) ([]byte, error) {
	if !goIdentifierPattern.MatchString(packageName) {
		return nil, fmt.Errorf("invalid generated package name %q", packageName)
	}
	modules := append([]ResolvedModule(nil), plan.Modules...)
	sort.Slice(modules, func(i, j int) bool { return modules[i].Descriptor.Module.ID < modules[j].Descriptor.Module.ID })
	aliases := map[string]string{}
	used := map[string]bool{}
	imports := map[string]string{}
	for _, resolved := range modules {
		if alias, exists := imports[resolved.Binding.ImportPath]; exists {
			aliases[resolved.Descriptor.Module.ID] = alias
			continue
		}
		alias := resolved.Binding.Package
		base := alias
		for n := 2; used[alias]; n++ {
			alias = base + strconv.Itoa(n)
		}
		used[alias] = true
		aliases[resolved.Descriptor.Module.ID] = alias
		imports[resolved.Binding.ImportPath] = alias
	}
	paths := make([]string, 0, len(imports))
	for path := range imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	var source strings.Builder
	source.WriteString("// Code generated by vivy-sdk. DO NOT EDIT.\npackage " + packageName + "\n\nimport (\n\t\"context\"\n\t\"errors\"\n\n\t\"agent-vivy/sdk/generation\"\n\t\"agent-vivy/sdk/module\"\n\t\"agent-vivy/sdk/port/channel\"\n\t\"agent-vivy/sdk/port/face\"\n\t\"agent-vivy/sdk/port/providerprofile\"\n\t\"agent-vivy/sdk/port/tool\"\n\t\"agent-vivy/sdk/port/toolworld\"\n")
	for _, path := range paths {
		fmt.Fprintf(&source, "\t%s %q\n", imports[path], path)
	}
	source.WriteString(")\n\ntype HostResolver interface {\n\tForModule(string) module.Host\n}\n\ntype RuntimeAssembly struct {\n\tTools []tool.ToolProvider\n\tWorlds []toolworld.Provider\n\tChannels []channel.ChannelProvider\n\tFace face.FaceProvider\n\tProviderProfiles []providerprofile.Provider\n\tDiagnosticObservers []toolworld.DiagnosticObserver\n\tDiagnosticObserverWorldIDs []string\n\tLanguageServerStatuses []toolworld.LanguageServerStatusProvider\n\tToolWorldGrants map[string][]module.GrantBinding\n\tChannelGrants map[string][]module.GrantBinding\n\tManifest generation.Manifest\n\towners []module.Instance\n}\n\nfunc BuildDefault() RuntimeAssembly {\n")
	var moduleIDs, channelNames, toolIDs, worldIDs, providerProfileIDs []string
	faceName := "kernel-headless"
	for _, resolved := range modules {
		moduleIDs = append(moduleIDs, resolved.Descriptor.Module.ID)
		for _, provided := range resolved.Descriptor.Provides {
			switch provided.Port {
			case "std/tool@v1":
				toolIDs = append(toolIDs, provided.ID)
			case "std/tool-world@v1":
				worldIDs = append(worldIDs, provided.ID)
			case "std/channel@v1":
				channelNames = append(channelNames, strings.TrimPrefix(provided.ID, "vivy."))
			case "std/face@v1":
				faceName = provided.ID
			case "std/provider-profile@v1":
				providerProfileIDs = append(providerProfileIDs, provided.ID)
			}
		}
	}
	providerValues := make(map[string]string)
	auxiliaryIndex := 0
	for _, resolved := range modules {
		binding := resolved.Binding
		if !binding.DiagnosticObserver && !binding.LanguageServerStatusProvider {
			continue
		}
		if binding.ProviderConstructor == "" || binding.ProviderCollection {
			return nil, fmt.Errorf("auxiliary ToolWorld binding for %s requires one Provider constructor", resolved.Descriptor.Module.ID)
		}
		hasWorld := false
		for _, provided := range resolved.Descriptor.Provides {
			hasWorld = hasWorld || provided.Port == "std/tool-world@v1"
		}
		if !hasWorld {
			return nil, fmt.Errorf("auxiliary ToolWorld binding for %s does not provide std/tool-world@v1", resolved.Descriptor.Module.ID)
		}
		name := "provider" + strconv.Itoa(auxiliaryIndex)
		auxiliaryIndex++
		providerValues[resolved.Descriptor.Module.ID] = name
		fmt.Fprintf(&source, "\t%s := %s.%s()\n", name, aliases[resolved.Descriptor.Module.ID], binding.ProviderConstructor)
	}
	source.WriteString("\treturn RuntimeAssembly{\n")
	// Emit slices separately to avoid duplicate field literals when a Module
	// contributes more than one public identity.
	type providerExpression struct {
		call       string
		collection bool
	}
	var toolsExpr, profilesExpr []providerExpression
	var worldsExpr, channelsExpr []string
	for _, resolved := range modules {
		alias := aliases[resolved.Descriptor.Module.ID]
		ctor := resolved.Binding.ProviderConstructor
		if ctor == "" {
			continue
		}
		hasTool, hasWorld, hasChannel, hasProfile := false, false, false, false
		for _, p := range resolved.Descriptor.Provides {
			hasTool = hasTool || p.Port == "std/tool@v1"
			hasWorld = hasWorld || p.Port == "std/tool-world@v1"
			hasChannel = hasChannel || p.Port == "std/channel@v1"
			hasProfile = hasProfile || p.Port == "std/provider-profile@v1"
		}
		call := alias + "." + ctor + "()"
		if value := providerValues[resolved.Descriptor.Module.ID]; value != "" {
			call = value
		}
		if hasTool {
			toolsExpr = append(toolsExpr, providerExpression{call: call, collection: resolved.Binding.ProviderCollection})
		}
		if hasWorld {
			worldsExpr = append(worldsExpr, call)
		}
		if hasChannel {
			channelsExpr = append(channelsExpr, call)
		}
		if hasProfile {
			profilesExpr = append(profilesExpr, providerExpression{call: call, collection: resolved.Binding.ProviderCollection})
		}
	}
	if len(toolsExpr) > 0 {
		tools := "[]tool.ToolProvider{}"
		for _, provider := range toolsExpr {
			if provider.collection {
				tools = "append(" + tools + ", " + provider.call + "...)"
			} else {
				tools = "append(" + tools + ", " + provider.call + ")"
			}
		}
		fmt.Fprintf(&source, "\t\tTools: %s,\n", tools)
	}
	if len(worldsExpr) > 0 {
		fmt.Fprintf(&source, "\t\tWorlds: []toolworld.Provider{%s},\n", strings.Join(worldsExpr, ","))
	}
	if len(profilesExpr) > 0 {
		profiles := "[]providerprofile.Provider{}"
		for _, provider := range profilesExpr {
			if provider.collection {
				profiles = "append(" + profiles + ", " + provider.call + "...)"
			} else {
				profiles = "append(" + profiles + ", " + provider.call + ")"
			}
		}
		fmt.Fprintf(&source, "\t\tProviderProfiles: %s,\n", profiles)
	}
	var observerExpr, observerWorldIDs, statusExpr []string
	for _, resolved := range modules {
		value := providerValues[resolved.Descriptor.Module.ID]
		if value == "" {
			continue
		}
		worldID := ""
		for _, provided := range resolved.Descriptor.Provides {
			if provided.Port == "std/tool-world@v1" {
				worldID = provided.ID
				break
			}
		}
		if resolved.Binding.DiagnosticObserver {
			observerExpr = append(observerExpr, value)
			observerWorldIDs = append(observerWorldIDs, strconv.Quote(worldID))
		}
		if resolved.Binding.LanguageServerStatusProvider {
			statusExpr = append(statusExpr, value)
		}
	}
	if len(observerExpr) > 0 {
		fmt.Fprintf(&source, "\t\tDiagnosticObservers: []toolworld.DiagnosticObserver{%s},\n", strings.Join(observerExpr, ","))
		fmt.Fprintf(&source, "\t\tDiagnosticObserverWorldIDs: []string{%s},\n", strings.Join(observerWorldIDs, ","))
	}
	if len(statusExpr) > 0 {
		fmt.Fprintf(&source, "\t\tLanguageServerStatuses: []toolworld.LanguageServerStatusProvider{%s},\n", strings.Join(statusExpr, ","))
	}
	if len(channelsExpr) > 0 {
		fmt.Fprintf(&source, "\t\tChannels: []channel.ChannelProvider{%s},\n", strings.Join(channelsExpr, ","))
	}
	writeGrants := func(grants []EffectiveGrant) {
		for _, grant := range grants {
			fmt.Fprintf(&source, "{Name: module.Grant(%q), Constraints: map[string][]string{", grant.Name)
			keys := make([]string, 0, len(grant.Constraints))
			for key := range grant.Constraints {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			for _, key := range keys {
				fmt.Fprintf(&source, "%q: {", key)
				for _, value := range grant.Constraints[key] {
					fmt.Fprintf(&source, "%q,", value)
				}
				source.WriteString("},")
			}
			source.WriteString("}},")
		}
	}
	source.WriteString("\t\tToolWorldGrants: map[string][]module.GrantBinding{\n")
	for _, resolved := range modules {
		for _, p := range resolved.Descriptor.Provides {
			if p.Port != "std/tool-world@v1" {
				continue
			}
			fmt.Fprintf(&source, "\t\t\t%q: {", p.ID)
			writeGrants(resolved.EffectiveGrants)
			source.WriteString("},\n")
		}
	}
	source.WriteString("\t\t},\n")
	for _, resolved := range modules {
		alias := aliases[resolved.Descriptor.Module.ID]
		ctor := resolved.Binding.ProviderConstructor
		if ctor == "" {
			continue
		}
		for _, p := range resolved.Descriptor.Provides {
			if p.Port == "std/face@v1" {
				fmt.Fprintf(&source, "\t\tFace: %s.%s(),\n", alias, ctor)
			}
		}
	}
	source.WriteString("\t\tChannelGrants: map[string][]module.GrantBinding{\n")
	for _, resolved := range modules {
		for _, p := range resolved.Descriptor.Provides {
			if p.Port != "std/channel@v1" {
				continue
			}
			fmt.Fprintf(&source, "\t\t\t%q: {", p.ID)
			writeGrants(resolved.EffectiveGrants)
			source.WriteString("},\n")
		}
	}
	source.WriteString("\t\t},\n\t\tManifest: generation.Manifest{\n")
	writeStrings := func(field string, values []string) {
		fmt.Fprintf(&source, "\t\t\t%s: []string{", field)
		for _, value := range values {
			fmt.Fprintf(&source, "%q,", value)
		}
		source.WriteString("},\n")
	}
	writeStrings("Modules", moduleIDs)
	writeStrings("Channels", channelNames)
	writeStrings("Tools", toolIDs)
	writeStrings("ToolWorlds", worldIDs)
	writeStrings("ProviderProfiles", providerProfileIDs)
	fmt.Fprintf(&source, "\t\t\tFace: %q,\n", faceName)
	channelState := "generation.NotCompiled"
	if len(channelNames) > 0 {
		channelState = "generation.Unconfigured"
	}
	mcpState := "generation.NotCompiled"
	for _, id := range worldIDs {
		if id == "mcp" {
			mcpState = "generation.Unconfigured"
			break
		}
	}
	fmt.Fprintf(&source, "\t\t\tNetworkStates: map[string]generation.CapabilityState{\"channels\": %s, \"mcp\": %s},\n\t\t},\n\t}\n}\n", channelState, mcpState)

	modulesByID := make(map[string]ResolvedModule, len(modules))
	for _, resolved := range modules {
		modulesByID[resolved.Descriptor.Module.ID] = resolved
	}
	source.WriteString("\nfunc (assembly *RuntimeAssembly) Start(ctx context.Context, hosts HostResolver) error {\n\tif assembly.owners != nil {\n\t\treturn errors.New(\"runtime assembly already started\")\n\t}\n\towners := make([]module.Instance, 0, ")
	source.WriteString(strconv.Itoa(len(plan.LifecycleOrder)))
	source.WriteString(")\n")
	for index, id := range plan.LifecycleOrder {
		resolved, ok := modulesByID[id]
		if !ok {
			return nil, fmt.Errorf("lifecycle module %s is not in AssemblyPlan", id)
		}
		if resolved.Binding.Constructor == "" {
			return nil, fmt.Errorf("missing lifecycle constructor for %s", id)
		}
		fmt.Fprintf(&source, "\towner%d, err := %s.%s().Construct(ctx, hosts.ForModule(%q))\n", index, aliases[id], resolved.Binding.Constructor, id)
		source.WriteString("\tif err != nil {\n\t\treturn errors.Join(err, closeOwners(ctx, owners))\n\t}\n")
		fmt.Fprintf(&source, "\towners = append(owners, owner%d)\n", index)
	}
	source.WriteString("\tfor index, owner := range owners {\n\t\tif err := owner.Start(ctx); err != nil {\n\t\t\treturn errors.Join(err, rollbackStart(ctx, owners, index+1))\n\t\t}\n\t\tif err := owner.Ready(ctx); err != nil {\n\t\t\treturn errors.Join(err, rollbackStart(ctx, owners, index+1))\n\t\t}\n\t}\n\tassembly.owners = owners\n\treturn nil\n}\n\nfunc (assembly *RuntimeAssembly) Close(ctx context.Context) error {\n\towners := assembly.owners\n\tassembly.owners = nil\n\treturn stopAndCloseOwners(ctx, owners)\n}\n\nfunc rollbackStart(ctx context.Context, owners []module.Instance, started int) error {\n\tvar failures []error\n\tfor index := started - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Stop(ctx))\n\t}\n\tfor index := len(owners) - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Close(ctx))\n\t}\n\treturn errors.Join(failures...)\n}\n\nfunc stopAndCloseOwners(ctx context.Context, owners []module.Instance) error {\n\tvar failures []error\n\tfor index := len(owners) - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Stop(ctx), owners[index].Close(ctx))\n\t}\n\treturn errors.Join(failures...)\n}\n\nfunc closeOwners(ctx context.Context, owners []module.Instance) error {\n\tvar failures []error\n\tfor index := len(owners) - 1; index >= 0; index-- {\n\t\tfailures = append(failures, owners[index].Close(ctx))\n\t}\n\treturn errors.Join(failures...)\n}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated runtime assembly: %w", err)
	}
	return formatted, nil
}
