package assembly

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"

	uiSDK "agent-vivy/sdk/ui"
)

// These constants mirror the public v1 Port catalog. Keeping the identities
// here makes the generated Assembly independent from runtime discovery and
// lets the compiler reject a contribution that is routed to the wrong Host.
const (
	UIExtensionPort = "std/ui-extension@v1"
	UIRootPort      = "std/ui-root@v1"

	UIAssemblyGeneratedMarker = "// Code generated by vivy-sdk. DO NOT EDIT."
)

// These compatibility values are initialized from sdk/ui's embedded
// package.json. Generation itself re-reads the same embedded metadata so a
// supplied Recipe pin cannot drift from the package used by Vite.
var (
	UIAssemblySDKPackageName = uiSDK.PackageName()
	UIAssemblySDKVersion     = uiSDK.Version()
)

// UIAssemblyErrorCode is deliberately closed. Callers can distinguish a
// malformed Recipe from an unavailable build input without parsing text.
type UIAssemblyErrorCode string

const (
	UIAssemblyErrorDuplicateRoot      UIAssemblyErrorCode = "duplicate_root"
	UIAssemblyErrorAmbiguousOrder     UIAssemblyErrorCode = "ambiguous_extension_order"
	UIAssemblyErrorMissingTarget      UIAssemblyErrorCode = "missing_target"
	UIAssemblyErrorFloatingDependency UIAssemblyErrorCode = "floating_dependency"
	UIAssemblyErrorRemoteEntry        UIAssemblyErrorCode = "remote_entry_url"
	UIAssemblyErrorMissingHash        UIAssemblyErrorCode = "missing_hash"
	UIAssemblyErrorInvalidPort        UIAssemblyErrorCode = "invalid_port"
	UIAssemblyErrorDuplicateID        UIAssemblyErrorCode = "duplicate_id"
	UIAssemblyErrorInvalidInput       UIAssemblyErrorCode = "invalid_input"
	UIAssemblyErrorSDKVersionMismatch UIAssemblyErrorCode = "sdk_version_mismatch"
	UIAssemblyErrorRootRelationship   UIAssemblyErrorCode = "root_relationship"
	UIAssemblyErrorConflictingAlias   UIAssemblyErrorCode = "conflicting_alias"
)

// UIAssemblyError names the exact contribution and rule that prevented
// generation. Secret values and filesystem contents are never included.
type UIAssemblyError struct {
	Code         UIAssemblyErrorCode
	Contribution string
	Detail       string
}

func (err *UIAssemblyError) Error() string {
	if err == nil {
		return "<nil>"
	}
	if err.Contribution == "" {
		return fmt.Sprintf("UI Assembly %s: %s", err.Code, err.Detail)
	}
	return fmt.Sprintf("UI Assembly %s (%s): %s", err.Code, err.Contribution, err.Detail)
}

// UIModule is the build-owned description of one selected full-code UI
// contribution. It is not a runtime registry entry. Entry is an explicit,
// package-relative TypeScript import specifier; it may never be a URL or an
// absolute machine path.
//
// ModuleID identifies the source Module for provenance. ID identifies the
// UI Provider exposed by that Module. For the common one-provider-per-module
// case ID may serve as both values.
type UIModule struct {
	ID         string `json:"id,omitempty" yaml:"id,omitempty"`
	ProviderID string `json:"providerId,omitempty" yaml:"providerId,omitempty"`
	ModuleID   string `json:"moduleId,omitempty" yaml:"moduleId,omitempty"`
	Port       string `json:"port,omitempty" yaml:"port,omitempty"`

	// Entry is a normalized ./ import confined to this Module's source tree;
	// package specifiers, URLs, absolute paths, and traversal are rejected.
	Entry      string `json:"entry,omitempty" yaml:"entry,omitempty"`
	ImportPath string `json:"importPath,omitempty" yaml:"importPath,omitempty"`
	Export     string `json:"export,omitempty" yaml:"export,omitempty"`
	ExportName string `json:"exportName,omitempty" yaml:"exportName,omitempty"`

	SourceHash   string `json:"sourceHash,omitempty" yaml:"sourceHash,omitempty"`
	SourceSHA256 string `json:"sourceSha256,omitempty" yaml:"sourceSha256,omitempty"`

	LockHash           string `json:"lockHash,omitempty" yaml:"lockHash,omitempty"`
	DependencyLockHash string `json:"dependencyLockHash,omitempty" yaml:"dependencyLockHash,omitempty"`

	AssetHash      string `json:"assetHash,omitempty" yaml:"assetHash,omitempty"`
	FinalAssetHash string `json:"finalAssetHash,omitempty" yaml:"finalAssetHash,omitempty"`

	// Dependencies are package.json dependency names and exact versions. A
	// lock hash alone does not make a floating package range a safe source
	// input, so ranges are rejected before imports are generated.
	Dependencies        map[string]string `json:"dependencies,omitempty" yaml:"dependencies,omitempty"`
	PackageDependencies map[string]string `json:"packageDependencies,omitempty" yaml:"packageDependencies,omitempty"`

	Before   []string `json:"before,omitempty" yaml:"before,omitempty"`
	After    []string `json:"after,omitempty" yaml:"after,omitempty"`
	Replaces []string `json:"replaces,omitempty" yaml:"replaces,omitempty"`
}

// UIAssemblyInput is the complete, explicit input to the UI generator. The
// generator only reads these values: it does not walk plugin directories,
// invoke a package manager, execute a shell command, or access the network.
type UIAssemblyInput struct {
	SDKVersion string `json:"sdkVersion" yaml:"sdkVersion"`

	// Roots is normally zero or one item. Root is a convenience for callers
	// constructing a single selected root without a slice.
	Root  UIModule   `json:"root,omitempty" yaml:"root,omitempty"`
	Roots []UIModule `json:"roots,omitempty" yaml:"roots,omitempty"`

	Extensions     []UIModule `json:"extensions,omitempty" yaml:"extensions,omitempty"`
	ExtensionOrder []string   `json:"extensionOrder,omitempty" yaml:"extensionOrder,omitempty"`
	// Order is an alias accepted for recipe adapters. Supplying both aliases
	// with different values is rejected as an ambiguous Recipe.
	Order []string `json:"order,omitempty" yaml:"order,omitempty"`

	// These maps allow a Recipe adapter to keep content-addressed inputs in a
	// separate manifest table. Per-module fields take precedence. Entries for
	// omitted Modules are intentionally ignored and never leak into output.
	SourceHashes         map[string]string `json:"sourceHashes,omitempty" yaml:"sourceHashes,omitempty"`
	DependencyLockHashes map[string]string `json:"dependencyLockHashes,omitempty" yaml:"dependencyLockHashes,omitempty"`
	LockHashes           map[string]string `json:"lockHashes,omitempty" yaml:"lockHashes,omitempty"`
	AssetHashes          map[string]string `json:"assetHashes,omitempty" yaml:"assetHashes,omitempty"`
	FinalAssetHashes     map[string]string `json:"finalAssetHashes,omitempty" yaml:"finalAssetHashes,omitempty"`
	// Catalogs is the validated, selected translation projection. It is an
	// explicit compiler input so generated hosts never discover catalogs at
	// runtime and catalog content participates in the sealed UI identity.
	Catalogs []CatalogManifest `json:"catalogs,omitempty" yaml:"catalogs,omitempty"`
}

func cloneUIAssemblyInput(source *UIAssemblyInput) *UIAssemblyInput {
	if source == nil {
		return nil
	}
	cloned := *source
	cloned.Root = cloneUIModule(source.Root)
	cloned.Roots = make([]UIModule, len(source.Roots))
	for index, contribution := range source.Roots {
		cloned.Roots[index] = cloneUIModule(contribution)
	}
	cloned.Extensions = make([]UIModule, len(source.Extensions))
	for index, contribution := range source.Extensions {
		cloned.Extensions[index] = cloneUIModule(contribution)
	}
	// Extension enumeration is not semantic once ExtensionOrder is explicit;
	// canonical Recipe bytes therefore sort this input-only list by stable
	// identity while preserving the separate order sequence.
	sort.SliceStable(cloned.Extensions, func(left, right int) bool {
		leftKey := cloned.Extensions[left].ID + "\x00" + cloned.Extensions[left].ModuleID + "\x00" + cloned.Extensions[left].Entry
		rightKey := cloned.Extensions[right].ID + "\x00" + cloned.Extensions[right].ModuleID + "\x00" + cloned.Extensions[right].Entry
		return leftKey < rightKey
	})
	cloned.ExtensionOrder = append([]string(nil), source.ExtensionOrder...)
	cloned.Order = append([]string(nil), source.Order...)
	cloned.SourceHashes = cloneStringMap(source.SourceHashes)
	cloned.DependencyLockHashes = cloneStringMap(source.DependencyLockHashes)
	cloned.LockHashes = cloneStringMap(source.LockHashes)
	cloned.AssetHashes = cloneStringMap(source.AssetHashes)
	cloned.FinalAssetHashes = cloneStringMap(source.FinalAssetHashes)
	cloned.Catalogs = cloneCatalogManifests(source.Catalogs)
	return &cloned
}

func cloneUIModule(source UIModule) UIModule {
	cloned := source
	cloned.Dependencies = cloneStringMap(source.Dependencies)
	cloned.PackageDependencies = cloneStringMap(source.PackageDependencies)
	cloned.Before = append([]string(nil), source.Before...)
	cloned.After = append([]string(nil), source.After...)
	cloned.Replaces = append([]string(nil), source.Replaces...)
	return cloned
}

// UIAssemblyManifest is the UI projection sealed into a Generation Manifest.
// Maps are keyed by selected Provider ID, and every selected contribution has
// one source, dependency-lock, SDK, and final asset identity.
type UIAssemblyManifest struct {
	Root                 string              `json:"root,omitempty"`
	Extensions           []string            `json:"extensions"`
	Replacements         map[string][]string `json:"replacements,omitempty"`
	SourceHashes         map[string]string   `json:"sourceHashes"`
	DependencyLockHashes map[string]string   `json:"dependencyLockHashes"`
	SDKPackage           string              `json:"sdkPackage"`
	SDKVersion           string              `json:"sdkVersion"`
	AssetHashes          map[string]string   `json:"assetHashes"`
	Catalogs             []CatalogManifest   `json:"catalogs,omitempty"`
}

// Canonical returns stable JSON suitable for inclusion in a content-addressed
// Generation identity. encoding/json sorts map keys; all slices were
// normalized before this manifest is returned.
func (manifest UIAssemblyManifest) Canonical() []byte {
	raw, err := json.Marshal(manifest)
	if err != nil {
		// All fields are strings/maps/slices populated by the generator, so this
		// is unreachable. Returning a deterministic empty object keeps this
		// convenience method total if a caller constructs an invalid value.
		return []byte("{}")
	}
	return raw
}

// UIAssembly is the generated TypeScript module and its sealed provenance.
// Generated and Code are compatibility spellings for build adapters; both
// contain the same immutable bytes as Source.
type UIAssembly struct {
	Source   []byte
	Manifest UIAssemblyManifest

	Generated []byte
	Code      []byte
}

var (
	uiDigestPattern        = regexp.MustCompile(`^[0-9a-f]{64}$`)
	uiCatalogModulePattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?/[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$`)
	uiSemverPattern        = regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$`)
	uiDependencyName       = regexp.MustCompile(`^(?:@[^/\s]+/)?[^/\s]+$`)
	uiImportSchemePattern  = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9+.-]*:`)
	uiIdentifierPattern    = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)
)

type normalizedUIModule struct {
	ID         string
	ModuleID   string
	Port       string
	Entry      string
	Export     string
	SourceHash string
	LockHash   string
	AssetHash  string
	Before     []string
	After      []string
	Replaces   []string
}

// GenerateUIAssembly validates and renders a deterministic, static UI
// composition. Every imported module is present in Roots or Extensions, in
// the explicit order selected by the Recipe adapter.
func GenerateUIAssembly(input UIAssemblyInput) (UIAssembly, error) {
	normalized, err := normalizeUIAssemblyInput(input)
	if err != nil {
		return UIAssembly{}, err
	}
	manifest := buildUIAssemblyManifest(normalized)
	source, err := renderUIAssembly(normalized, manifest)
	if err != nil {
		return UIAssembly{}, err
	}
	return UIAssembly{
		Source:    source,
		Manifest:  manifest,
		Generated: append([]byte(nil), source...),
		Code:      append([]byte(nil), source...),
	}, nil
}

// GenerateUIAssemblySource is the source-only adapter used by build tools
// that seal the returned manifest through SealInputs themselves.
func GenerateUIAssemblySource(input UIAssemblyInput) ([]byte, error) {
	result, err := GenerateUIAssembly(input)
	if err != nil {
		return nil, err
	}
	return result.Source, nil
}

// GenerateUIComposition is an intentionally descriptive alias for callers
// whose build pipeline names the generated artifact a composition.
func GenerateUIComposition(input UIAssemblyInput) ([]byte, error) {
	return GenerateUIAssemblySource(input)
}

// CompileUI is an alias used by Assembly adapters. It remains pure and
// deterministic; compilation of TypeScript is a separate explicit build
// step whose output hash is supplied back as AssetHash.
func CompileUI(input UIAssemblyInput) (UIAssembly, error) {
	return GenerateUIAssembly(input)
}

func normalizeUIAssemblyInput(input UIAssemblyInput) (normalizedUIAssembly, error) {
	pin, err := uiSDK.PinnedPackage()
	if err != nil {
		return normalizedUIAssembly{}, uiAssemblyError(UIAssemblyErrorInvalidInput, "", err.Error())
	}
	if strings.TrimSpace(input.SDKVersion) == "" {
		return normalizedUIAssembly{}, uiAssemblyError(UIAssemblyErrorInvalidInput, "", "SDK version is required")
	}
	if input.SDKVersion != pin.Version {
		return normalizedUIAssembly{}, uiAssemblyError(UIAssemblyErrorSDKVersionMismatch, "", fmt.Sprintf("SDK version %q does not match pinned UI SDK %s@%s", input.SDKVersion, pin.Name, pin.Version))
	}

	rootInputs := append([]UIModule(nil), input.Roots...)
	if uiModulePresent(input.Root) {
		rootInputs = append(rootInputs, input.Root)
	}
	if len(rootInputs) > 1 {
		return normalizedUIAssembly{}, uiAssemblyError(UIAssemblyErrorDuplicateRoot, "", "std/ui-root@v1 accepts exactly one selected root")
	}

	roots := make([]normalizedUIModule, 0, len(rootInputs))
	for _, contribution := range rootInputs {
		normalized, err := normalizeUIModule(contribution, UIRootPort, input)
		if err != nil {
			return normalizedUIAssembly{}, err
		}
		if len(normalized.Before) > 0 || len(normalized.After) > 0 || len(normalized.Replaces) > 0 {
			return normalizedUIAssembly{}, uiAssemblyError(UIAssemblyErrorRootRelationship, normalized.ID, "root relationship edges are not supported by the single-root UI Assembly")
		}
		roots = append(roots, normalized)
	}

	extensions := make([]normalizedUIModule, 0, len(input.Extensions))
	for _, contribution := range input.Extensions {
		normalized, err := normalizeUIModule(contribution, UIExtensionPort, input)
		if err != nil {
			return normalizedUIAssembly{}, err
		}
		extensions = append(extensions, normalized)
	}
	sort.SliceStable(extensions, func(left, right int) bool {
		return normalizedUIModuleSortKey(extensions[left]) < normalizedUIModuleSortKey(extensions[right])
	})

	all := make([]normalizedUIModule, 0, len(roots)+len(extensions))
	all = append(all, roots...)
	all = append(all, extensions...)
	byID := make(map[string]normalizedUIModule, len(all))
	for _, contribution := range all {
		if _, exists := byID[contribution.ID]; exists {
			return normalizedUIAssembly{}, uiAssemblyError(UIAssemblyErrorDuplicateID, contribution.ID, "UI provider id is selected more than once")
		}
		byID[contribution.ID] = contribution
	}
	if err := validateUIRelationshipTargets(all, byID); err != nil {
		return normalizedUIAssembly{}, err
	}

	order, err := resolveUIExtensionOrder(extensions, input.ExtensionOrder, input.Order)
	if err != nil {
		return normalizedUIAssembly{}, err
	}
	orderedExtensions := make([]normalizedUIModule, 0, len(order))
	for _, id := range order {
		orderedExtensions = append(orderedExtensions, byID[id])
	}

	catalogs, err := normalizeCatalogManifests(input.Catalogs)
	if err != nil {
		return normalizedUIAssembly{}, err
	}
	return normalizedUIAssembly{SDKPackage: pin.Name, SDKVersion: pin.Version, Root: roots, Extensions: orderedExtensions, Catalogs: catalogs}, nil
}

type normalizedUIAssembly struct {
	SDKPackage string
	SDKVersion string
	Root       []normalizedUIModule
	Extensions []normalizedUIModule
	Catalogs   []CatalogManifest
}

func normalizeCatalogManifests(input []CatalogManifest) ([]CatalogManifest, error) {
	if len(input) == 0 {
		return nil, nil
	}
	catalogs := cloneCatalogManifests(input)
	seen := make(map[string]struct{}, len(catalogs))
	seenKeys := make(map[string]string)
	for index := range catalogs {
		catalog := &catalogs[index]
		catalog.Module = strings.TrimSpace(catalog.Module)
		if catalog.Module == "" {
			return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, "", "catalog module is required")
		}
		if !uiCatalogModulePattern.MatchString(catalog.Module) {
			return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, "catalog module namespace is invalid")
		}
		if _, exists := seen[catalog.Module]; exists {
			return nil, uiAssemblyError(UIAssemblyErrorDuplicateID, catalog.Module, "catalog is selected more than once")
		}
		seen[catalog.Module] = struct{}{}
		apiVersion := strings.TrimSpace(catalog.APIVersion)
		schemaVersion := strings.TrimSpace(catalog.SchemaVersion)
		if apiVersion != "" && schemaVersion != "" && apiVersion != schemaVersion {
			return nil, uiAssemblyError(UIAssemblyErrorConflictingAlias, catalog.Module, fmt.Sprintf("conflicting catalog apiVersion aliases %q and %q", apiVersion, schemaVersion))
		}
		version := firstNonEmpty(apiVersion, schemaVersion)
		if version != "vivy.i18n/v1" {
			return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, "catalog apiVersion must be vivy.i18n/v1")
		}
		catalog.APIVersion = version
		catalog.SchemaVersion = version
		if catalog.DefaultLocale != "en" {
			return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, "catalog defaultLocale must be en")
		}
		if !containsString(catalog.Locales, "en") {
			return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, "catalog locales must include en")
		}
		if !uiDigestPattern.MatchString(catalog.Digest) || catalog.Digest != catalogProjectionDigest(*catalog) {
			return nil, uiAssemblyError(UIAssemblyErrorMissingHash, catalog.Module, "catalog digest does not match its sealed translation projection")
		}
		if len(catalog.Units) == 0 {
			return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, "catalog requires translation units")
		}
		prefix := "plugin." + catalog.Module + "."
		for key, unit := range catalog.Units {
			if previous, exists := seenKeys[key]; exists {
				return nil, uiAssemblyError(UIAssemblyErrorDuplicateID, catalog.Module, fmt.Sprintf("translation key %q is claimed by catalogs %s and %s", key, previous, catalog.Module))
			}
			seenKeys[key] = catalog.Module
			if !strings.HasPrefix(key, prefix) || len(key) == len(prefix) {
				return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, fmt.Sprintf("catalog key %q is outside owner namespace", key))
			}
			if len(unit.Messages) == 0 || strings.TrimSpace(unit.Messages["en"]) == "" {
				return nil, uiAssemblyError(UIAssemblyErrorInvalidInput, catalog.Module, fmt.Sprintf("catalog unit %q requires an English message", key))
			}
		}
	}
	sort.Slice(catalogs, func(left, right int) bool { return catalogs[left].Module < catalogs[right].Module })
	return catalogs, nil
}

func containsString(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func catalogProjectionDigest(catalog CatalogManifest) string {
	payload := struct {
		APIVersion string                 `json:"apiVersion"`
		Units      map[string]CatalogUnit `json:"units"`
	}{APIVersion: catalog.APIVersion, Units: catalog.Units}
	raw, err := json.Marshal(payload)
	if err != nil {
		return ""
	}
	digest := sha256.Sum256(raw)
	return hex.EncodeToString(digest[:])
}

func normalizeUIModule(contribution UIModule, expectedPort string, input UIAssemblyInput) (normalizedUIModule, error) {
	id, err := chooseStringAlias("provider id", contribution.ID, contribution.ProviderID)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, "", err.Error())
	}
	if id == "" {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorInvalidInput, "", "UI provider id is required")
	}
	moduleID := strings.TrimSpace(contribution.ModuleID)
	if moduleID == "" {
		moduleID = id
	}
	portName := strings.TrimSpace(contribution.Port)
	if portName == "" {
		portName = expectedPort
	}
	if portName != expectedPort {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorInvalidPort, id, fmt.Sprintf("provider declares %s; expected %s", portName, expectedPort))
	}

	entry, err := chooseStringAlias("entry", contribution.Entry, contribution.ImportPath)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
	}
	if strings.TrimSpace(contribution.Entry) != contribution.Entry || strings.TrimSpace(contribution.ImportPath) != contribution.ImportPath {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorRemoteEntry, id, "entry is not a source-confined normalized relative import: leading or trailing whitespace is forbidden")
	}
	if entry == "" {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorInvalidInput, id, "explicit TypeScript entry is required")
	}
	if err := validateUIEntry(id, entry); err != nil {
		return normalizedUIModule{}, err
	}

	exportName, err := chooseStringAlias("export", contribution.Export, contribution.ExportName)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
	}
	if exportName == "" {
		exportName = "default"
	}
	if exportName != "default" && !uiIdentifierPattern.MatchString(exportName) {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorInvalidInput, id, fmt.Sprintf("export %q is not a TypeScript identifier", exportName))
	}

	sourceHash, err := chooseStringAlias("source hash", contribution.SourceHash, contribution.SourceSHA256)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
	}
	if sourceHash == "" {
		sourceHash, err = lookupHashAliases("source hash", []string{moduleID, id}, input.SourceHashes)
		if err != nil {
			return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
		}
	}
	if err := validateUIHash(id, "source", sourceHash); err != nil {
		return normalizedUIModule{}, err
	}
	lockHash, err := chooseStringAlias("dependency lock hash", contribution.LockHash, contribution.DependencyLockHash)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
	}
	if lockHash == "" {
		lockHash, err = lookupHashAliases("dependency lock hash", []string{moduleID, id}, input.DependencyLockHashes, input.LockHashes)
		if err != nil {
			return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
		}
	}
	if err := validateUIHash(id, "dependency lock", lockHash); err != nil {
		return normalizedUIModule{}, err
	}
	assetHash, err := chooseStringAlias("asset hash", contribution.AssetHash, contribution.FinalAssetHash)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
	}
	if assetHash == "" {
		assetHash, err = lookupHashAliases("asset hash", []string{moduleID, id}, input.AssetHashes, input.FinalAssetHashes)
		if err != nil {
			return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorConflictingAlias, id, err.Error())
		}
	}
	if err := validateUIHash(id, "asset", assetHash); err != nil {
		return normalizedUIModule{}, err
	}

	dependencies, err := mergeDependencies(contribution.Dependencies, contribution.PackageDependencies)
	if err != nil {
		return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorInvalidInput, id, err.Error())
	}
	dependencyNames := make([]string, 0, len(dependencies))
	for name := range dependencies {
		dependencyNames = append(dependencyNames, name)
	}
	sort.Strings(dependencyNames)
	for _, name := range dependencyNames {
		version := dependencies[name]
		if !uiDependencyName.MatchString(name) || !uiSemverPattern.MatchString(version) {
			return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorFloatingDependency, id, fmt.Sprintf("floating package dependency %s@%s", name, version))
		}
	}
	for _, relation := range []struct {
		name   string
		values []string
	}{
		{name: "before", values: contribution.Before},
		{name: "after", values: contribution.After},
		{name: "replaces", values: contribution.Replaces},
	} {
		for _, target := range relation.values {
			if strings.TrimSpace(target) == "" {
				return normalizedUIModule{}, uiAssemblyError(UIAssemblyErrorMissingTarget, id, relation.name+" relationship has a blank relationship target")
			}
		}
	}

	return normalizedUIModule{
		ID:         id,
		ModuleID:   moduleID,
		Port:       portName,
		Entry:      entry,
		Export:     exportName,
		SourceHash: sourceHash,
		LockHash:   lockHash,
		AssetHash:  assetHash,
		Before:     canonicalRelationValues(contribution.Before),
		After:      canonicalRelationValues(contribution.After),
		Replaces:   canonicalRelationValues(contribution.Replaces),
	}, nil
}

func validateUIEntry(id, entry string) error {
	invalid := func(detail string) error {
		return uiAssemblyError(UIAssemblyErrorRemoteEntry, id, fmt.Sprintf("entry %q is not a source-confined normalized relative import: %s", entry, detail))
	}
	if strings.HasPrefix(entry, "//") || uiImportSchemePattern.MatchString(entry) || strings.HasPrefix(entry, "/") {
		return invalid("remote entry URLs, schemes, and absolute paths are forbidden")
	}
	if strings.ContainsAny(entry, "\x00\r\n\t\"\\?#:") {
		return invalid("control characters, backslashes, fragments, queries, and drive/scheme separators are forbidden")
	}
	if !strings.HasPrefix(entry, "./") {
		return invalid("the import must begin with ./ and cannot be a bare package specifier")
	}
	clean := path.Clean(entry)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, "../") {
		return invalid("path traversal escapes the selected Module source")
	}
	normalized := "./" + strings.TrimPrefix(clean, "./")
	if entry != normalized {
		return invalid(fmt.Sprintf("path is not normalized; want %q", normalized))
	}
	return nil
}

func validateUIHash(id, label, value string) error {
	if value == "" {
		return uiAssemblyError(UIAssemblyErrorMissingHash, id, label+" hash is required as an explicit input")
	}
	if !uiDigestPattern.MatchString(value) {
		return uiAssemblyError(UIAssemblyErrorInvalidInput, id, fmt.Sprintf("%s hash must be 64 lowercase hexadecimal characters", label))
	}
	return nil
}

func validateUIRelationshipTargets(all []normalizedUIModule, byID map[string]normalizedUIModule) error {
	replacementOwners := make(map[string]string)
	for _, contribution := range all {
		for _, relation := range []struct {
			name   string
			values []string
		}{
			{name: "before", values: contribution.Before},
			{name: "after", values: contribution.After},
			{name: "replaces", values: contribution.Replaces},
		} {
			relationName, values := relation.name, relation.values
			for _, target := range values {
				targetContribution, exists := byID[target]
				if !exists {
					return uiAssemblyError(UIAssemblyErrorMissingTarget, contribution.ID, fmt.Sprintf("missing target %s for %s relationship", target, relationName))
				}
				if target == contribution.ID {
					return uiAssemblyError(UIAssemblyErrorMissingTarget, contribution.ID, fmt.Sprintf("%s relationship cannot target itself", relationName))
				}
				// The single root is installed outside the extension sequence. An
				// extension edge targeting it would otherwise disappear in
				// uiExtensionGraph, silently changing the requested composition.
				if targetContribution.Port == UIRootPort {
					return uiAssemblyError(UIAssemblyErrorRootRelationship, contribution.ID, fmt.Sprintf("%s relationship targeting root %s is not supported by the single-root UI Assembly", relationName, target))
				}
				if relationName == "replaces" {
					if owner, exists := replacementOwners[target]; exists && owner != contribution.ID {
						return uiAssemblyError(UIAssemblyErrorAmbiguousOrder, contribution.ID, fmt.Sprintf("replacement target %s is claimed by both %s and %s", target, owner, contribution.ID))
					}
					replacementOwners[target] = contribution.ID
				}
			}
		}
	}
	return nil
}

func resolveUIExtensionOrder(extensions []normalizedUIModule, explicit, alias []string) ([]string, error) {
	if len(explicit) > 0 && len(alias) > 0 && !equalStrings(explicit, alias) {
		return nil, uiAssemblyError(UIAssemblyErrorAmbiguousOrder, "", "ExtensionOrder and Order disagree")
	}
	if len(explicit) == 0 {
		explicit = alias
	}
	if len(extensions) == 0 {
		if len(explicit) > 0 {
			return nil, uiAssemblyError(UIAssemblyErrorAmbiguousOrder, "", "extension order names providers but no extensions are selected")
		}
		return nil, nil
	}
	if len(explicit) == 0 {
		return nil, uiAssemblyError(UIAssemblyErrorAmbiguousOrder, "", "ambiguous extension order: ExtensionOrder is required for every selected std/ui-extension@v1 provider")
	}

	edges := uiExtensionGraph(extensions)
	orderAliases := uiExtensionOrderAliases(extensions)
	seen := make(map[string]struct{}, len(explicit))
	positions := make(map[string]int, len(explicit))
	ordered := make([]string, len(explicit))
	for index, rawID := range explicit {
		orderID := strings.TrimSpace(rawID)
		id, knownExtension := orderAliases.providerIDs[orderID]
		if !knownExtension {
			providers := orderAliases.moduleIDs[orderID]
			if len(providers) > 1 {
				return nil, uiAssemblyError(UIAssemblyErrorAmbiguousOrder, orderID, fmt.Sprintf("ambiguous ModuleID %s identifies providers %s", orderID, strings.Join(providers, ", ")))
			}
			if len(providers) == 1 {
				id = providers[0]
				knownExtension = true
			}
		}
		if !knownExtension {
			return nil, uiAssemblyError(UIAssemblyErrorMissingTarget, orderID, "explicit extension order names a missing target")
		}
		if _, duplicate := seen[id]; duplicate {
			return nil, uiAssemblyError(UIAssemblyErrorAmbiguousOrder, id, "explicit extension order contains a duplicate")
		}
		seen[id] = struct{}{}
		positions[id] = index
		ordered[index] = id
	}
	for _, extension := range extensions {
		if _, listed := seen[extension.ID]; !listed {
			return nil, uiAssemblyError(UIAssemblyErrorAmbiguousOrder, extension.ID, "explicit extension order omits a selected extension")
		}
	}
	if err := validateUIOrderEdges(edges, positions); err != nil {
		return nil, err
	}
	return ordered, nil
}

type uiExtensionOrderAliasSet struct {
	providerIDs map[string]string
	moduleIDs   map[string][]string
}

func uiExtensionOrderAliases(extensions []normalizedUIModule) uiExtensionOrderAliasSet {
	aliases := uiExtensionOrderAliasSet{
		providerIDs: make(map[string]string, len(extensions)),
		moduleIDs:   make(map[string][]string, len(extensions)),
	}
	for _, extension := range extensions {
		aliases.providerIDs[extension.ID] = extension.ID
		aliases.moduleIDs[extension.ModuleID] = append(aliases.moduleIDs[extension.ModuleID], extension.ID)
	}
	for moduleID, providerIDs := range aliases.moduleIDs {
		sort.Strings(providerIDs)
		aliases.moduleIDs[moduleID] = providerIDs
	}
	return aliases
}

func uiExtensionGraph(extensions []normalizedUIModule) map[string]map[string]struct{} {
	edges := make(map[string]map[string]struct{}, len(extensions))
	for _, extension := range extensions {
		edges[extension.ID] = make(map[string]struct{})
	}
	add := func(from, to string) {
		if _, fromIsExtension := edges[from]; !fromIsExtension {
			return
		}
		if _, toIsExtension := edges[to]; !toIsExtension {
			return
		}
		if _, exists := edges[from][to]; exists {
			return
		}
		edges[from][to] = struct{}{}
	}
	for _, extension := range extensions {
		for _, target := range extension.Before {
			add(extension.ID, target)
		}
		for _, target := range extension.After {
			add(target, extension.ID)
		}
		// Replacing an extension is installed after the target so that the
		// replacement can deterministically undo or supersede it.
		for _, target := range extension.Replaces {
			add(target, extension.ID)
		}
	}
	return edges
}

func validateUIOrderEdges(edges map[string]map[string]struct{}, positions map[string]int) error {
	fromIDs := make([]string, 0, len(edges))
	for from := range edges {
		fromIDs = append(fromIDs, from)
	}
	sort.Strings(fromIDs)
	for _, from := range fromIDs {
		successors := edges[from]
		toIDs := make([]string, 0, len(successors))
		for to := range successors {
			toIDs = append(toIDs, to)
		}
		sort.Strings(toIDs)
		for _, to := range toIDs {
			if positions[from] >= positions[to] {
				return uiAssemblyError(UIAssemblyErrorAmbiguousOrder, from, fmt.Sprintf("order conflict: %s must be before %s", from, to))
			}
		}
	}
	return nil
}

func normalizedUIModuleSortKey(contribution normalizedUIModule) string {
	return contribution.ID + "\x00" + contribution.ModuleID + "\x00" + contribution.Entry
}

func buildUIAssemblyManifest(assembly normalizedUIAssembly) UIAssemblyManifest {
	manifest := UIAssemblyManifest{
		Extensions:           make([]string, 0, len(assembly.Extensions)),
		Replacements:         make(map[string][]string),
		SourceHashes:         make(map[string]string, len(assembly.Root)+len(assembly.Extensions)),
		DependencyLockHashes: make(map[string]string, len(assembly.Root)+len(assembly.Extensions)),
		SDKPackage:           assembly.SDKPackage,
		SDKVersion:           assembly.SDKVersion,
		AssetHashes:          make(map[string]string, len(assembly.Root)+len(assembly.Extensions)),
		Catalogs:             cloneCatalogManifests(assembly.Catalogs),
	}
	all := append(append([]normalizedUIModule(nil), assembly.Root...), assembly.Extensions...)
	if len(assembly.Root) == 1 {
		manifest.Root = assembly.Root[0].ID
	}
	for _, contribution := range all {
		manifest.SourceHashes[contribution.ID] = contribution.SourceHash
		manifest.DependencyLockHashes[contribution.ID] = contribution.LockHash
		manifest.AssetHashes[contribution.ID] = contribution.AssetHash
		if len(contribution.Replaces) > 0 {
			manifest.Replacements[contribution.ID] = append([]string(nil), contribution.Replaces...)
		}
	}
	for _, contribution := range assembly.Extensions {
		manifest.Extensions = append(manifest.Extensions, contribution.ID)
	}
	if len(manifest.Replacements) == 0 {
		manifest.Replacements = nil
	}
	return manifest
}

func renderUIAssembly(assembly normalizedUIAssembly, manifest UIAssemblyManifest) ([]byte, error) {
	var source strings.Builder
	source.WriteString(UIAssemblyGeneratedMarker + "\n\n")
	fmt.Fprintf(&source, "import type { UIExtension, UIRoot } from %s;\n\n", quoteJSON(assembly.SDKPackage))

	all := append(append([]normalizedUIModule(nil), assembly.Root...), assembly.Extensions...)
	for index, contribution := range all {
		fmt.Fprintf(&source, "import * as __vivy_ui_module_%d from %s;\n", index, quoteJSON(contribution.Entry))
	}
	if len(all) > 0 {
		source.WriteString("\n")
	}

	manifestJSON, err := json.Marshal(manifest)
	if err != nil {
		return nil, fmt.Errorf("marshal UI Assembly manifest: %w", err)
	}
	source.WriteString("export const UI_ASSEMBLY_MANIFEST = Object.freeze(")
	source.Write(manifestJSON)
	source.WriteString(");\n\n")

	if len(assembly.Root) == 1 {
		fmt.Fprintf(&source, "export const uiRoot: UIRoot | undefined = __vivy_ui_module_0.%s as UIRoot;\n", assembly.Root[0].Export)
	} else {
		source.WriteString("export const uiRoot: UIRoot | undefined = undefined;\n")
	}
	source.WriteString("\nexport const uiExtensions: readonly UIExtension[] = [")
	for index, contribution := range assembly.Extensions {
		if index > 0 {
			source.WriteString(", ")
		}
		moduleIndex := len(assembly.Root) + index
		fmt.Fprintf(&source, "__vivy_ui_module_%d.%s as UIExtension", moduleIndex, contribution.Export)
	}
	source.WriteString("];\n\n")
	source.WriteString("export const generatedUIRoot = uiRoot;\n")
	source.WriteString("export const generatedUIExtensions = uiExtensions;\n")
	source.WriteString("export const uiAssembly = Object.freeze({ root: uiRoot, extensions: uiExtensions, manifest: UI_ASSEMBLY_MANIFEST });\n")
	source.WriteString("export const UI_ROOT = uiRoot;\n")
	source.WriteString("export const UI_EXTENSIONS = uiExtensions;\n")
	return []byte(source.String()), nil
}

func quoteJSON(value string) string {
	raw, _ := json.Marshal(value)
	return string(raw)
}

func uiAssemblyError(code UIAssemblyErrorCode, contribution, detail string) error {
	return &UIAssemblyError{Code: code, Contribution: contribution, Detail: detail}
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

func chooseStringAlias(name, first, second string) (string, error) {
	first = strings.TrimSpace(first)
	second = strings.TrimSpace(second)
	if first != "" && second != "" && first != second {
		return "", fmt.Errorf("conflicting %s aliases %q and %q", name, first, second)
	}
	return firstNonEmpty(first, second), nil
}

func uiModulePresent(module UIModule) bool {
	return module.ID != "" || module.ProviderID != "" || module.ModuleID != "" || module.Port != "" ||
		module.Entry != "" || module.ImportPath != "" || module.Export != "" || module.ExportName != "" ||
		module.SourceHash != "" || module.SourceSHA256 != "" || module.LockHash != "" || module.DependencyLockHash != "" ||
		module.AssetHash != "" || module.FinalAssetHash != "" || len(module.Dependencies) > 0 || len(module.PackageDependencies) > 0 ||
		len(module.Before) > 0 || len(module.After) > 0 || len(module.Replaces) > 0
}

func lookupHashAliases(name string, keys []string, values ...map[string]string) (string, error) {
	type candidate struct {
		alias string
		value string
	}
	candidates := make([]candidate, 0, len(keys)*len(values))
	for valueIndex, valuesMap := range values {
		for keyIndex, key := range keys {
			value := strings.TrimSpace(valuesMap[key])
			if value == "" {
				continue
			}
			candidates = append(candidates, candidate{
				alias: fmt.Sprintf("%d:%d:%s", valueIndex, keyIndex, key),
				value: value,
			})
		}
	}
	if len(candidates) == 0 {
		return "", nil
	}
	sort.Slice(candidates, func(left, right int) bool {
		return candidates[left].alias < candidates[right].alias
	})
	for _, candidate := range candidates[1:] {
		if candidate.value != candidates[0].value {
			return "", fmt.Errorf("conflicting %s aliases for %s", name, strings.Join(keys, ", "))
		}
	}
	return candidates[0].value, nil
}

func mergeDependencies(first, second map[string]string) (map[string]string, error) {
	merged := make(map[string]string, len(first)+len(second))
	for name, version := range first {
		merged[name] = strings.TrimSpace(version)
	}
	for name, version := range second {
		version = strings.TrimSpace(version)
		if previous, exists := merged[name]; exists && previous != version {
			return nil, fmt.Errorf("dependency %s has conflicting versions %s and %s", name, previous, version)
		}
		merged[name] = version
	}
	return merged, nil
}

func canonicalRelationValues(values []string) []string {
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value != "" {
			set[value] = struct{}{}
		}
	}
	result := make([]string, 0, len(set))
	for value := range set {
		result = append(result, value)
	}
	sort.Strings(result)
	return result
}

func equalStrings(first, second []string) bool {
	if len(first) != len(second) {
		return false
	}
	for index := range first {
		if first[index] != second[index] {
			return false
		}
	}
	return true
}

// HashUIAssemblySource is a convenience for build adapters that want to
// content-address the generated projection before invoking the frontend
// compiler. The final emitted asset hash must still be supplied explicitly as
// AssetHash; a source hash is not an asset hash.
func HashUIAssemblySource(source []byte) string {
	digest := sha256.Sum256(source)
	return hex.EncodeToString(digest[:])
}
