#!/usr/bin/env python3
"""Regenerate ui/src/components/settings/provider-catalog.ts from the
Agent-Diva provider registry (ui/agent-diva-source/agent-diva-providers/src/providers.yaml).

Run from the repository root or the ui/ directory:

    python ui/scripts/gen-provider-catalog.py

Porting rules (Agent-Diva -> Vivy):
- api_type 'anthropic' maps to the vivy runtime bundle 'anthropic'; everything
  else (diva api_type 'openai') maps to bundle 'openai'.
- default_model keeps its raw model id only: the leading `<name>/` or
  `<gateway_prefix>/` gateway prefix is stripped (Vivy sends raw model ids).
- The diva 'custom' entry keeps no recommended model (its 'custom/default'
  placeholder is not a real model id).
- Data bug fixed on import: aionly's default_api_base carries a stray
  full-width colon prefix in the yaml; it is normalized here.
- The vivy-local 'mock' bundle is appended (offline dev / UI test path).
"""

from pathlib import Path
import yaml

UI_ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = UI_ROOT / "agent-diva-source" / "agent-diva-providers" / "src" / "providers.yaml"
OUT_PATH = UI_ROOT / "src" / "components" / "settings" / "provider-catalog.ts"

# Agent-Diva ProvidersSettings.vue hiddenProviderNames, kept verbatim.
FOLDED = [
    "302ai", "aihubmix", "aionly", "baichuan", "burncloud", "cephalon",
    "cerebras", "cherryin", "fireworks", "hyperbolic", "infini", "jina",
    "lanyun", "ocoolai", "ph8", "ppio", "together", "tokenflux",
    "voyageai", "yi",
]

MOCK_ENTRY = {
    "name": "mock",
    "displayName": "Mock",
    "bundle": "mock",
    "baseUrl": "",
    "defaultModel": "mock",
    "models": ["mock"],
}


def strip_gateway_prefix(model: str, name: str, gateway_prefix: str) -> str:
    for prefix in (f"{name}/", f"{gateway_prefix}/" if gateway_prefix else ""):
        if prefix and model.startswith(prefix):
            return model[len(prefix):]
    return model


def load_entries():
    with YAML_PATH.open(encoding="utf-8") as handle:
        raw = yaml.safe_load(handle)
    entries = []
    for item in raw:
        name = item["name"]
        gateway = item.get("gateway_prefix") or ""
        base_url = (item.get("default_api_base") or "").strip()
        if base_url.startswith("："):
            base_url = base_url.lstrip("：")
        default_model = item.get("default_model") or ""
        if name == "custom":
            default_model = ""
        elif default_model:
            default_model = strip_gateway_prefix(default_model, name, gateway)
        else:
            models = item.get("models") or []
            default_model = models[0] if models else ""
        entries.append({
            "name": name,
            "displayName": item["display_name"],
            "bundle": "anthropic" if item.get("api_type") == "anthropic" else "openai",
            "baseUrl": base_url,
            "defaultModel": default_model,
            "models": list(item.get("models") or []),
        })
    entries.append(dict(MOCK_ENTRY))
    return entries


def ts_str(value: str) -> str:
    assert "'" not in value, f"unescaped quote in {value!r}"
    return f"'{value}'"


def format_entry(entry) -> str:
    head = (
        f"  {{ name: {ts_str(entry['name'])}, displayName: {ts_str(entry['displayName'])}, "
        f"bundle: '{entry['bundle']}', baseUrl: {ts_str(entry['baseUrl'])}, "
        f"defaultModel: {ts_str(entry['defaultModel'])}, "
    )
    models = ", ".join(ts_str(model) for model in entry["models"])
    if len(entry["models"]) <= 4:
        return f"{head}models: [{models}] }},"
    lines = [head + "models: ["]
    for model in entry["models"]:
        lines.append(f"    {ts_str(model)},")
    lines.append("  ] },")
    return "\n".join(lines)


HEADER = """\
// AUTO-GENERATED by ui/scripts/gen-provider-catalog.py — do not edit the data
// array by hand. Source of truth: Agent-Diva provider registry
// (ui/agent-diva-source/agent-diva-providers/src/providers.yaml).
//
// Agent-Diva 的供应商目录移植：目录条目按厂商展示，但 Vivy 后端 settings 只
// 接受 openai/anthropic/mock 三个运行束名，厂商差异通过 base_url 网关表达。
// 选择条目时映射为 (bundle, baseUrl, defaultModel) 三元组，模型 id 始终为
// 原始 id（不携带网关前缀）。

export type ProviderRuntimeBundle = 'openai' | 'anthropic' | 'mock';

export type ProviderCatalogEntry = {
  /** Agent-Diva 供应商 id（如 'deepseek'），仅用于目录展示与检索 */
  name: string;
  displayName: string;
  /** Vivy 运行时模型束名（settings.provider 的合法取值） */
  bundle: ProviderRuntimeBundle;
  /** OpenAI 兼容网关地址；空表示使用运行束默认地址 */
  baseUrl: string;
  /** 推荐默认模型（原始模型 id）；空表示目录未给出推荐 */
  defaultModel: string;
  /** 静态模型列表（原始模型 id） */
  models: string[];
};

export const PROVIDER_CATALOG: readonly ProviderCatalogEntry[] = [
"""

FOOTER = """\
];

/** 默认折叠进“更多供应商”分组的供应商 id（与 Agent-Diva hiddenProviderNames 一致） */
export const FOLDED_PROVIDER_NAMES: ReadonlySet<string> = new Set([
__FOLDED__
]);

export function findProvider(name: string): ProviderCatalogEntry | undefined {
  return PROVIDER_CATALOG.find((entry) => entry.name === name);
}

export function isFoldedProvider(name: string): boolean {
  return FOLDED_PROVIDER_NAMES.has(name);
}

/** 按 displayName / name 检索；空串返回全部（与 Agent-Diva 的过滤口径一致） */
export function searchProviders(term: string): readonly ProviderCatalogEntry[] {
  const needle = term.trim().toLowerCase();
  if (!needle) return PROVIDER_CATALOG;
  return PROVIDER_CATALOG.filter(
    (entry) => entry.displayName.toLowerCase().includes(needle) || entry.name.toLowerCase().includes(needle),
  );
}

export type ProviderFoldGroups = {
  visible: readonly ProviderCatalogEntry[];
  more: readonly ProviderCatalogEntry[];
};

/** 搜索时绕过折叠（more 恒为空），否则按折叠名单拆分 */
export function splitByFold(entries: readonly ProviderCatalogEntry[], searching: boolean): ProviderFoldGroups {
  if (searching) return { visible: entries, more: [] };
  return {
    visible: entries.filter((entry) => !FOLDED_PROVIDER_NAMES.has(entry.name)),
    more: entries.filter((entry) => FOLDED_PROVIDER_NAMES.has(entry.name)),
  };
}

/** 用 settings/form 的 (provider, base_url) 反查目录条目；base_url 为空时回落到与运行束同名的规范条目 */
export function matchProviderEntry(bundle: string, baseUrl: string): ProviderCatalogEntry | undefined {
  const base = baseUrl.trim();
  if (base) return PROVIDER_CATALOG.find((entry) => entry.bundle === bundle && entry.baseUrl === base);
  return PROVIDER_CATALOG.find((entry) => entry.name === bundle && entry.bundle === bundle);
}
"""


def main() -> None:
    entries = load_entries()
    names = [entry["name"] for entry in entries]
    assert len(names) == len(set(names)), "duplicate provider names"
    unknown = [name for name in FOLDED if name not in names]
    assert not unknown, f"folded names missing from catalog: {unknown}"

    folded_block = "\n".join(f"  {ts_str(name)}," for name in FOLDED)
    body = HEADER + "\n".join(format_entry(entry) for entry in entries) + "\n" + FOOTER.replace("__FOLDED__", folded_block)
    OUT_PATH.write_text(body, encoding="utf-8", newline="\n")
    print(f"wrote {OUT_PATH} ({len(entries)} entries, {len(FOLDED)} folded)")


if __name__ == "__main__":
    main()
