
ALTER TABLE messages ADD COLUMN tool_call_id TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN tool_name TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN tool_args BLOB NOT NULL DEFAULT '';
