// AUTO-GENERATED by ui/scripts/gen-provider-catalog.py — do not edit the data
// array by hand. Source of truth: Agent-Diva provider registry
// (ui/agent-diva-source/agent-diva-providers/src/providers.yaml).
//
// Agent-Diva 的供应商目录移植：目录条目按厂商展示，但 Vivy 后端 settings 只
// 接受 openai/anthropic/mock 三个运行束名，厂商差异通过 base_url 网关表达。
// 选择条目时映射为 (bundle, baseUrl, defaultModel) 三元组，模型 id 始终为
// 原始 id（不携带网关前缀）。

export type ProviderRuntimeBundle = 'openai' | 'anthropic' | 'mock';

export type ProviderCatalogEntry = {
  /** Agent-Diva 供应商 id（如 'deepseek'），仅用于目录展示与检索 */
  name: string;
  displayName: string;
  /** Vivy 运行时模型束名（settings.provider 的合法取值） */
  bundle: ProviderRuntimeBundle;
  /** OpenAI 兼容网关地址；空表示使用运行束默认地址 */
  baseUrl: string;
  /** 推荐默认模型（原始模型 id）；空表示目录未给出推荐 */
  defaultModel: string;
  /** 静态模型列表（原始模型 id） */
  models: string[];
};

export const PROVIDER_CATALOG: readonly ProviderCatalogEntry[] = [
  { name: 'openrouter', displayName: 'OpenRouter', bundle: 'openai', baseUrl: 'https://openrouter.ai/api/v1', defaultModel: 'anthropic/claude-sonnet-4', models: [
    'google/gemini-2.5-flash-preview',
    'qwen/qwen-2.5-7b-instruct:free',
    'deepseek/deepseek-chat',
    'mistralai/mistral-7b-instruct:free',
    'google/gemini-2.0-flash-exp:free',
    'deepseek/deepseek-r1:free',
    'qwen/qwen-2.5-vl-72b-instruct:free',
  ] },
  { name: 'aihubmix', displayName: 'AiHubMix', bundle: 'openai', baseUrl: 'https://aihubmix.com/v1', defaultModel: 'claude-sonnet-4', models: [
    'gpt-4o',
    'claude-3-5-sonnet-20240620',
    'deepseek-chat',
    'gpt-5',
    'gpt-5-mini',
    'o3',
    'DeepSeek-V3',
    'DeepSeek-R1',
    'gemini-2.5-pro',
    'gemini-2.5-flash',
    'kimi-k2-0711-preview',
  ] },
  { name: 'custom', displayName: 'Custom / Local', bundle: 'openai', baseUrl: 'http://localhost:8000/v1', defaultModel: '', models: [] },
  { name: 'anthropic', displayName: 'Anthropic', bundle: 'anthropic', baseUrl: 'https://api.anthropic.com', defaultModel: 'claude-sonnet-4-5', models: [
    'claude-3-5-sonnet-20240620',
    'claude-3-opus-20240229',
    'claude-3-sonnet-20240229',
    'claude-3-haiku-20240307',
    'claude-opus-4-6',
    'claude-sonnet-4-5',
    'claude-haiku-4-5',
    'claude-opus-4-5',
  ] },
  { name: 'openai', displayName: 'OpenAI', bundle: 'openai', baseUrl: 'https://api.openai.com/v1', defaultModel: 'gpt-4o', models: [
    'gpt-4o',
    'gpt-4o-mini',
    'gpt-4-turbo',
    'gpt-4',
    'gpt-3.5-turbo',
    'o1-preview',
    'o1-mini',
    'gpt-5.1',
    'gpt-5',
    'gpt-5-mini',
    'gpt-5-nano',
    'gpt-5-pro',
    'gpt-5-chat',
    'gpt-image-1',
  ] },
  { name: 'deepseek', displayName: 'DeepSeek', bundle: 'openai', baseUrl: 'https://api.deepseek.com/v1', defaultModel: 'deepseek-v4-pro', models: [
    'deepseek-v4-pro',
    'deepseek-v4-flash',
    'deepseek-chat',
    'deepseek-coder',
    'deepseek-reasoner',
  ] },
  { name: 'gemini', displayName: 'Gemini', bundle: 'openai', baseUrl: 'https://generativelanguage.googleapis.com/v1beta', defaultModel: 'gemini-2.0-flash', models: [
    'gemini-1.5-pro',
    'gemini-1.5-flash',
    'gemini-2.0-flash-exp',
    'gemini-2.5-flash',
    'gemini-2.5-pro',
    'gemini-3-pro-preview',
  ] },
  { name: 'zhipu', displayName: 'Zhipu AI', bundle: 'openai', baseUrl: 'https://open.bigmodel.cn/api/paas/v4', defaultModel: 'glm-4-flash', models: [
    'glm-4',
    'glm-4-air',
    'glm-4-flash',
    'glm-3-turbo',
    'glm-5',
    'glm-4.7',
    'glm-4.6',
    'glm-4.5',
    'embedding-3',
  ] },
  { name: 'dashscope', displayName: 'DashScope', bundle: 'openai', baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', defaultModel: 'qwen-max', models: [
    'qwen-max',
    'qwen-plus',
    'qwen-turbo',
    'qwen-vl-max',
    'qwen-vl-plus',
    'qwen3-max',
    'qwen3.5-plus',
    'text-embedding-v3',
  ] },
  { name: 'moonshot', displayName: 'Moonshot', bundle: 'openai', baseUrl: 'https://api.moonshot.cn/v1', defaultModel: 'moonshot-v1-8k', models: [
    'moonshot-v1-8k',
    'moonshot-v1-32k',
    'moonshot-v1-128k',
    'kimi-k2.5',
    'kimi-k2-thinking',
  ] },
  { name: 'minimax', displayName: 'MiniMax', bundle: 'openai', baseUrl: 'https://api.minimaxi.com/v1', defaultModel: 'MiniMax-M2.1', models: [
    'abab6.5-chat',
    'abab6.5s-chat',
    'abab5.5-chat',
    'MiniMax-M2.5',
    'MiniMax-M2',
  ] },
  { name: 'vllm', displayName: 'vLLM/Local', bundle: 'openai', baseUrl: 'http://localhost:11434/v1', defaultModel: 'meta-llama/Llama-3.3-70B-Instruct', models: [] },
  { name: 'groq', displayName: 'Groq', bundle: 'openai', baseUrl: 'https://api.groq.com/openai/v1', defaultModel: 'llama-3.3-70b-versatile', models: [
    'llama3-8b-8192',
    'llama3-70b-8192',
    'mixtral-8x7b-32768',
    'gemma-7b-it',
    'mistral-saba-24b',
    'gemma-9b-it',
  ] },
  { name: 'xai', displayName: 'xAI', bundle: 'openai', baseUrl: 'https://api.x.ai/v1', defaultModel: 'grok-beta', models: ['grok-beta', 'grok-vision-beta', 'grok-4', 'grok-3'] },
  { name: 'cherryin', displayName: 'CherryIN', bundle: 'openai', baseUrl: 'https://open.cherryin.cc/v1', defaultModel: '', models: [] },
  { name: '302ai', displayName: '302.AI', bundle: 'openai', baseUrl: 'https://api.302.ai/v1', defaultModel: 'deepseek-chat', models: [
    'deepseek-chat',
    'deepseek-reasoner',
    'chatgpt-4o-latest',
    'o3',
    'claude-sonnet-4-20250514',
  ] },
  { name: 'ph8', displayName: 'PH8', bundle: 'openai', baseUrl: 'https://ph8.co/v1', defaultModel: 'deepseek-v3-241226', models: ['deepseek-v3-241226', 'deepseek-r1-250120'] },
  { name: 'burncloud', displayName: 'BurnCloud', bundle: 'openai', baseUrl: 'https://ai.burncloud.com/v1', defaultModel: 'claude-opus-4-5-20251101', models: ['claude-opus-4-5-20251101', 'gpt-5', 'gemini-2.5-flash', 'deepseek-reasoner'] },
  { name: 'silicon', displayName: 'SiliconFlow', bundle: 'openai', baseUrl: 'https://api.siliconflow.cn/v1', defaultModel: 'deepseek-ai/DeepSeek-V3.2', models: ['deepseek-ai/DeepSeek-V3.2', 'Qwen/Qwen3-8B'] },
  { name: 'ppio', displayName: 'PPIO', bundle: 'openai', baseUrl: 'https://api.ppinfra.com/v3/openai', defaultModel: 'deepseek/deepseek-v3.2', models: ['deepseek/deepseek-v3.2', 'minimax/minimax-m2', 'qwen/qwen3-235b-a22b-instruct-2507'] },
  { name: 'together', displayName: 'Together AI', bundle: 'openai', baseUrl: 'https://api.together.xyz/v1', defaultModel: 'meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo', models: ['meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo', 'google/gemma-2-27b-it'] },
  { name: 'ocoolai', displayName: 'OcoolAI', bundle: 'openai', baseUrl: 'https://api.ocoolai.com/v1', defaultModel: 'deepseek-chat', models: ['deepseek-chat', 'gpt-4o', 'claude-3-5-sonnet-20240620', 'gemini-1.5-pro'] },
  { name: 'github', displayName: 'GitHub Models', bundle: 'openai', baseUrl: 'https://models.inference.ai.azure.com', defaultModel: 'gpt-4o', models: ['gpt-4o'] },
  { name: 'yi', displayName: 'Yi (01.AI)', bundle: 'openai', baseUrl: 'https://api.lingyiwanwu.com/v1', defaultModel: 'yi-lightning', models: ['yi-lightning', 'yi-vision-v2'] },
  { name: 'baichuan', displayName: 'Baichuan', bundle: 'openai', baseUrl: 'https://api.baichuan-ai.com/v1', defaultModel: 'Baichuan4', models: ['Baichuan4', 'Baichuan3-Turbo', 'Baichuan4-Air'] },
  { name: 'modelscope', displayName: 'ModelScope', bundle: 'openai', baseUrl: 'https://api-inference.modelscope.cn/v1', defaultModel: 'Qwen/Qwen2.5-72B-Instruct', models: ['Qwen/Qwen2.5-72B-Instruct', 'deepseek-ai/DeepSeek-V3'] },
  { name: 'stepfun', displayName: 'StepFun', bundle: 'openai', baseUrl: 'https://api.stepfun.com/v1', defaultModel: 'step-1-8k', models: ['step-1-8k', 'step-1-flash'] },
  { name: 'doubao', displayName: 'Doubao (Ark)', bundle: 'openai', baseUrl: 'https://ark.cn-beijing.volces.com/api/v3', defaultModel: 'doubao-pro-32k', models: ['doubao-pro-32k', 'doubao-lite-32k'] },
  { name: 'hyperbolic', displayName: 'Hyperbolic', bundle: 'openai', baseUrl: 'https://api.hyperbolic.xyz/v1', defaultModel: 'meta-llama/Meta-Llama-3.1-405B', models: ['meta-llama/Meta-Llama-3.1-405B', 'Qwen/Qwen2-VL-72B-Instruct'] },
  { name: 'mistral', displayName: 'Mistral AI', bundle: 'openai', baseUrl: 'https://api.mistral.ai/v1', defaultModel: 'mistral-large-latest', models: ['mistral-large-latest', 'mistral-small-latest', 'pixtral-12b-2409'] },
  { name: 'jina', displayName: 'Jina AI', bundle: 'openai', baseUrl: 'https://api.jina.ai/v1', defaultModel: 'jina-embeddings-v3', models: ['jina-embeddings-v3', 'jina-clip-v2'] },
  { name: 'fireworks', displayName: 'Fireworks AI', bundle: 'openai', baseUrl: 'https://api.fireworks.ai/inference/v1', defaultModel: 'accounts/fireworks/models/llama-v3-70b-instruct', models: ['accounts/fireworks/models/llama-v3-70b-instruct'] },
  { name: 'hunyuan', displayName: 'Hunyuan', bundle: 'openai', baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1', defaultModel: 'hunyuan-pro', models: ['hunyuan-pro', 'hunyuan-standard', 'hunyuan-lite'] },
  { name: 'nvidia', displayName: 'NVIDIA NIM', bundle: 'openai', baseUrl: 'https://integrate.api.nvidia.com/v1', defaultModel: 'meta/llama-3.1-405b-instruct', models: ['meta/llama-3.1-405b-instruct'] },
  { name: 'baidu-cloud', displayName: 'Baidu Qianfan', bundle: 'openai', baseUrl: 'https://qianfan.baidubce.com/v2', defaultModel: 'ernie-4.0-8k-latest', models: ['ernie-4.0-8k-latest', 'ernie-speed-8k'] },
  { name: 'perplexity', displayName: 'Perplexity', bundle: 'openai', baseUrl: 'https://api.perplexity.ai', defaultModel: 'sonar-pro', models: ['sonar-pro', 'sonar-reasoning'] },
  { name: 'infini', displayName: 'Infini / Maas', bundle: 'openai', baseUrl: 'https://cloud.infini-ai.com/maas/v1', defaultModel: 'deepseek-r1', models: ['deepseek-r1', 'deepseek-v3', 'qwen2.5-72b-instruct'] },
  { name: 'voyageai', displayName: 'Voyage AI', bundle: 'openai', baseUrl: 'https://api.voyageai.com/v1', defaultModel: 'voyage-3', models: ['voyage-3', 'voyage-code-3'] },
  { name: 'qiniu', displayName: 'Qiniu', bundle: 'openai', baseUrl: 'https://api.qnaigc.com/v1', defaultModel: 'deepseek-r1', models: ['deepseek-r1', 'deepseek-v3'] },
  { name: 'tokenflux', displayName: 'TokenFlux', bundle: 'openai', baseUrl: 'https://api.tokenflux.ai/openai/v1', defaultModel: 'gpt-4.1', models: ['gpt-4.1', 'claude-3-7-sonnet'] },
  { name: 'cephalon', displayName: 'Cephalon', bundle: 'openai', baseUrl: 'https://cephalon.cloud/user-center/v1', defaultModel: 'DeepSeek-R1', models: ['DeepSeek-R1'] },
  { name: 'lanyun', displayName: 'Lanyun', bundle: 'openai', baseUrl: 'https://maas-api.lanyun.net/v1', defaultModel: 'deepseek-ai/DeepSeek-R1', models: ['deepseek-ai/DeepSeek-R1', 'Qwen/Qwen2.5-72B-Instruct'] },
  { name: 'poe', displayName: 'Poe', bundle: 'openai', baseUrl: 'https://api.poe.com/v1', defaultModel: 'gpt-4o', models: ['gpt-4o'] },
  { name: 'aionly', displayName: 'AIOnly', bundle: 'openai', baseUrl: 'https://api.aiionly.com/v1', defaultModel: 'gpt-5.1', models: ['gpt-5.1', 'claude-opus-4-5-20251101'] },
  { name: 'longcat', displayName: 'LongCat', bundle: 'openai', baseUrl: 'https://api.longcat.chat/openai/v1', defaultModel: 'LongCat-Flash-Chat', models: ['LongCat-Flash-Chat'] },
  { name: 'cerebras', displayName: 'Cerebras', bundle: 'openai', baseUrl: 'https://api.cerebras.ai/v1', defaultModel: 'gpt-oss-120b', models: ['gpt-oss-120b', 'zai-glm-4.6'] },
  { name: 'mimo', displayName: 'Mimo', bundle: 'openai', baseUrl: 'https://api.xiaomimimo.com/v1', defaultModel: 'mimo-v2-flash', models: ['mimo-v2-flash'] },
  { name: 'mock', displayName: 'Mock', bundle: 'mock', baseUrl: '', defaultModel: 'mock', models: ['mock'] },
];

/** 默认折叠进“更多供应商”分组的供应商 id（与 Agent-Diva hiddenProviderNames 一致） */
export const FOLDED_PROVIDER_NAMES: ReadonlySet<string> = new Set([
  '302ai',
  'aihubmix',
  'aionly',
  'baichuan',
  'burncloud',
  'cephalon',
  'cerebras',
  'cherryin',
  'fireworks',
  'hyperbolic',
  'infini',
  'jina',
  'lanyun',
  'ocoolai',
  'ph8',
  'ppio',
  'together',
  'tokenflux',
  'voyageai',
  'yi',
]);

export function findProvider(name: string): ProviderCatalogEntry | undefined {
  return PROVIDER_CATALOG.find((entry) => entry.name === name);
}

export function isFoldedProvider(name: string): boolean {
  return FOLDED_PROVIDER_NAMES.has(name);
}

/** 按 displayName / name 检索；空串返回全部（与 Agent-Diva 的过滤口径一致） */
export function searchProviders(term: string): readonly ProviderCatalogEntry[] {
  const needle = term.trim().toLowerCase();
  if (!needle) return PROVIDER_CATALOG;
  return PROVIDER_CATALOG.filter(
    (entry) => entry.displayName.toLowerCase().includes(needle) || entry.name.toLowerCase().includes(needle),
  );
}

export type ProviderFoldGroups = {
  visible: readonly ProviderCatalogEntry[];
  more: readonly ProviderCatalogEntry[];
};

/** 搜索时绕过折叠（more 恒为空），否则按折叠名单拆分 */
export function splitByFold(entries: readonly ProviderCatalogEntry[], searching: boolean): ProviderFoldGroups {
  if (searching) return { visible: entries, more: [] };
  return {
    visible: entries.filter((entry) => !FOLDED_PROVIDER_NAMES.has(entry.name)),
    more: entries.filter((entry) => FOLDED_PROVIDER_NAMES.has(entry.name)),
  };
}

/** 用 settings/form 的 (provider, base_url) 反查目录条目；base_url 为空时回落到与运行束同名的规范条目 */
export function matchProviderEntry(bundle: string, baseUrl: string): ProviderCatalogEntry | undefined {
  const base = baseUrl.trim();
  if (base) return PROVIDER_CATALOG.find((entry) => entry.bundle === bundle && entry.baseUrl === base);
  return PROVIDER_CATALOG.find((entry) => entry.name === bundle && entry.bundle === bundle);
}
