import { useEffect } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useVivyStore } from '@/lib/store';
import { useTranslation } from '@/i18n';

export function LifecycleView() {
  const { t } = useTranslation();
  const species = useVivyStore((state) => state.species); const generations = useVivyStore((state) => state.generations); const evals = useVivyStore((state) => state.evals); const promotions = useVivyStore((state) => state.promotions); const phase = useVivyStore((state) => state.lifecyclePhase); const error = useVivyStore((state) => state.lifecycleError);
  const load = useVivyStore((state) => state.loadLifecycle);
  useEffect(() => { void load(); }, [load]);
  if (phase === 'loading' && !species) return <div className="h-full overflow-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4"><div className="h-10 w-64 animate-pulse rounded bg-muted"/><div className="h-72 animate-pulse rounded-xl bg-muted"/></div></div>;
  return <div className="h-full overflow-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold">{t('lifecycle.title')}</h1><p className="mt-1 text-sm text-muted-foreground">{t('lifecycle.subtitle')}</p></div><Button variant="outline" className="self-start sm:self-auto" onClick={() => void load()}>{t('common.refresh')}</Button></div><p className="mb-4 text-sm text-muted-foreground">{t('lifecycle.readonlyNote')}</p>{error ? <p className="mb-4 rounded bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}<Tabs defaultValue="species"><TabsList><TabsTrigger value="species">{t('lifecycle.speciesTab')}</TabsTrigger><TabsTrigger value="generations">{t('lifecycle.generationsTab')}</TabsTrigger><TabsTrigger value="evals">{t('lifecycle.evalsTab')}</TabsTrigger><TabsTrigger value="promotions">{t('lifecycle.promotionsTab')}</TabsTrigger></TabsList>
    <TabsContent value="species"><Card><CardHeader><CardTitle>{t('lifecycle.currentSpecies')}</CardTitle><CardDescription>{species?.binary_id || t('lifecycle.noBinary')}</CardDescription></CardHeader><CardContent className="space-y-4 text-sm">{species ? <><dl className="grid grid-cols-1 gap-2 sm:grid-cols-[160px_minmax(0,1fr)]"><dt className="text-muted-foreground">{t('lifecycle.protocol')}</dt><dd>{species.protocol_version}</dd><dt className="text-muted-foreground">{t('hostLabels.generation')}</dt><dd>{species.generation_id || t('lifecycle.notSet')}</dd><dt className="text-muted-foreground">{t('hostLabels.artifactSha')}</dt><dd className="break-all font-mono text-xs">{species.artifact_sha256 || t('lifecycle.notSet')}</dd><dt className="text-muted-foreground">{t('hostLabels.policy')}</dt><dd>{species.policy_profile} · {species.policy_hash}</dd></dl><div><h3 className="font-medium">{t('lifecycle.recipe')}</h3><pre className="mt-2 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(species.recipe, null, 2)}</pre></div><div><h3 className="font-medium">{t('lifecycle.toolsGrants')}</h3><div className="mt-2 flex flex-wrap gap-2">{species.tools.map((tool) => <Badge key={tool.name} variant="outline">{tool.readonly ? t('hostLabels.readonlyTool', { name: tool.name }) : tool.name}</Badge>)}{species.grants.map((grant) => <Badge key={grant} variant="secondary">{grant}</Badge>)}</div></div></> : <p className="text-muted-foreground">{t('lifecycle.speciesUnavailable')}</p>}</CardContent></Card></TabsContent>
    <TabsContent value="generations" className="space-y-2">{generations.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><span className="truncate font-medium">{item.id}</span><Badge variant="outline">{item.phase}</Badge></div><p className="truncate font-mono text-xs text-muted-foreground">{item.artifact_sha256}</p></div></CardContent></Card>)}</TabsContent>
    <TabsContent value="evals" className="space-y-2">{evals.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="break-words font-medium">{t('hostLabels.comparison', { candidate: item.candidate_id, baseline: item.baseline_id || t('lifecycle.baselineMissing') })}</div><div className="text-xs text-muted-foreground">{item.suite}</div></div><Badge className="self-start sm:self-auto">{item.verdict}</Badge></CardContent></Card>)}</TabsContent>
    <TabsContent value="promotions" className="space-y-2">{promotions.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="break-words font-medium">{item.from_id} → {item.to_id}</div><div className="text-xs text-muted-foreground">{item.actor} · {item.applies_at}</div></div><Badge className="self-start sm:self-auto">{item.phase}</Badge></CardContent></Card>)}</TabsContent>
  </Tabs></div></div>;
}
