import { useEffect, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useVivyStore } from '@/lib/store';
import type { EvalVerdict } from '@/lib/api';

const csv = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
export function LifecycleView() {
  const species = useVivyStore((state) => state.species); const generations = useVivyStore((state) => state.generations); const evals = useVivyStore((state) => state.evals); const promotions = useVivyStore((state) => state.promotions); const phase = useVivyStore((state) => state.lifecyclePhase); const error = useVivyStore((state) => state.lifecycleError); const busy = useVivyStore((state) => state.lifecycleBusy);
  const load = useVivyStore((state) => state.loadLifecycle); const createGeneration = useVivyStore((state) => state.createGeneration); const rejectGeneration = useVivyStore((state) => state.rejectGeneration); const startEval = useVivyStore((state) => state.startEval); const recordEval = useVivyStore((state) => state.recordEval); const promote = useVivyStore((state) => state.promoteGeneration);
  const [generation, setGeneration] = useState({ artifact: '', parent: '', source: '', loop: '', world: '', providers: '', tools: '', plugins: '' });
  const [evalForm, setEvalForm] = useState({ candidate: '', baseline: '', suite: '' }); const [recordForm, setRecordForm] = useState({ candidate: '', baseline: '', suite: '', verdict: 'mixed' as EvalVerdict, journal: '' }); const [promotion, setPromotion] = useState({ from: '', to: '', evalId: '', actor: 'human' });
  useEffect(() => { void load(); }, [load]);
  if (phase === 'loading' && !species) return <div className="h-full overflow-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4"><div className="h-10 w-64 animate-pulse rounded bg-muted"/><div className="h-72 animate-pulse rounded-xl bg-muted"/></div></div>;
  return <div className="h-full overflow-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold">生命周期</h1><p className="mt-1 text-sm text-muted-foreground">检查 Vivy species，并管理 Generation、Eval 和 Promotion。</p></div><Button variant="outline" className="self-start sm:self-auto" onClick={() => void load()}>刷新</Button></div>{error ? <p className="mb-4 rounded bg-destructive/10 p-3 text-sm text-destructive">{error}</p> : null}<Tabs defaultValue="species"><TabsList><TabsTrigger value="species">Species</TabsTrigger><TabsTrigger value="generations">Generations</TabsTrigger><TabsTrigger value="evals">Evals</TabsTrigger><TabsTrigger value="promotions">Promotions</TabsTrigger></TabsList>
    <TabsContent value="species"><Card><CardHeader><CardTitle>当前 Species</CardTitle><CardDescription>{species?.binary_id || '未配置 binary'}</CardDescription></CardHeader><CardContent className="space-y-4 text-sm">{species ? <><dl className="grid grid-cols-1 gap-2 sm:grid-cols-[160px_minmax(0,1fr)]"><dt className="text-muted-foreground">协议</dt><dd>{species.protocol_version}</dd><dt className="text-muted-foreground">Generation</dt><dd>{species.generation_id || '未设置'}</dd><dt className="text-muted-foreground">Artifact SHA</dt><dd className="break-all font-mono text-xs">{species.artifact_sha256 || '未设置'}</dd><dt className="text-muted-foreground">Policy</dt><dd>{species.policy_profile} · {species.policy_hash}</dd></dl><div><h3 className="font-medium">Recipe</h3><pre className="mt-2 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(species.recipe, null, 2)}</pre></div><div><h3 className="font-medium">工具与 Grants</h3><div className="mt-2 flex flex-wrap gap-2">{species.tools.map((tool) => <Badge key={tool.name} variant="outline">{tool.name}{tool.readonly ? ' · read-only' : ''}</Badge>)}{species.grants.map((grant) => <Badge key={grant} variant="secondary">{grant}</Badge>)}</div></div></> : <p className="text-muted-foreground">Species inspect 不可用</p>}</CardContent></Card></TabsContent>
    <TabsContent value="generations" className="space-y-4"><Card><CardHeader><CardTitle>创建 Generation</CardTitle><CardDescription>登记一个已经构建的 artifact；此操作不会执行安装。</CardDescription></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-2" onSubmit={async (event) => { event.preventDefault(); await createGeneration({ artifact_sha256: generation.artifact, parent_id: generation.parent || undefined, source_ref: generation.source || undefined, recipe: { loop: generation.loop || undefined, world: generation.world || undefined, providers: csv(generation.providers), tools: csv(generation.tools), plugins: csv(generation.plugins) } }); setGeneration({ ...generation, artifact: '' }); }}><Field label="Artifact SHA256"><Input required value={generation.artifact} onChange={(event) => setGeneration({ ...generation, artifact: event.target.value })}/></Field><Field label="Parent ID"><Input value={generation.parent} onChange={(event) => setGeneration({ ...generation, parent: event.target.value })}/></Field><Field label="Source ref"><Input value={generation.source} onChange={(event) => setGeneration({ ...generation, source: event.target.value })}/></Field><Field label="Loop"><Input value={generation.loop} onChange={(event) => setGeneration({ ...generation, loop: event.target.value })}/></Field><Field label="World"><Input value={generation.world} onChange={(event) => setGeneration({ ...generation, world: event.target.value })}/></Field><Field label="Providers（逗号分隔）"><Input value={generation.providers} onChange={(event) => setGeneration({ ...generation, providers: event.target.value })}/></Field><Field label="Tools（逗号分隔）"><Input value={generation.tools} onChange={(event) => setGeneration({ ...generation, tools: event.target.value })}/></Field><Field label="Plugins（逗号分隔）"><Input value={generation.plugins} onChange={(event) => setGeneration({ ...generation, plugins: event.target.value })}/></Field><div className="md:col-span-2"><Button type="submit" disabled={busy || !generation.artifact.trim()}>创建 Generation</Button></div></form></CardContent></Card><div className="space-y-2">{generations.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><span className="truncate font-medium">{item.id}</span><Badge variant="outline">{item.phase}</Badge></div><p className="truncate font-mono text-xs text-muted-foreground">{item.artifact_sha256}</p></div>{!['rejected', 'released'].includes(item.phase) ? <Button variant="destructive" size="sm" className="self-start sm:self-auto" disabled={busy} onClick={() => { if (window.confirm(`拒绝 Generation ${item.id}？`)) void rejectGeneration(item.id); }}>拒绝</Button> : null}</CardContent></Card>)}</div></TabsContent>
    <TabsContent value="evals" className="space-y-4"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>启动评测</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={async (event) => { event.preventDefault(); await startEval({ candidate_id: evalForm.candidate, baseline_id: evalForm.baseline || undefined, suite: evalForm.suite }); }}><GenerationSelect label="Candidate" value={evalForm.candidate} onChange={(candidate) => setEvalForm({ ...evalForm, candidate })} generations={generations}/><GenerationSelect label="Baseline（可选）" value={evalForm.baseline} onChange={(baseline) => setEvalForm({ ...evalForm, baseline })} generations={generations} optional/><Field label="Suite"><Input required value={evalForm.suite} onChange={(event) => setEvalForm({ ...evalForm, suite: event.target.value })}/></Field><Button type="submit" disabled={busy || !evalForm.candidate || !evalForm.suite}>启动</Button></form></CardContent></Card><Card><CardHeader><CardTitle>记录外部评测</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={async (event) => { event.preventDefault(); await recordEval({ candidate_id: recordForm.candidate, baseline_id: recordForm.baseline || undefined, suite: recordForm.suite, verdict: recordForm.verdict, journal_ref: recordForm.journal || undefined }); }}><GenerationSelect label="Candidate" value={recordForm.candidate} onChange={(candidate) => setRecordForm({ ...recordForm, candidate })} generations={generations}/><Field label="Suite"><Input required value={recordForm.suite} onChange={(event) => setRecordForm({ ...recordForm, suite: event.target.value })}/></Field><Field label="Verdict"><Select value={recordForm.verdict} onValueChange={(verdict) => setRecordForm({ ...recordForm, verdict: verdict as EvalVerdict })}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['better', 'worse', 'mixed', 'failed_to_run'].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field><Field label="Journal ref（可选）"><Input value={recordForm.journal} onChange={(event) => setRecordForm({ ...recordForm, journal: event.target.value })}/></Field><Button type="submit" disabled={busy || !recordForm.candidate || !recordForm.suite}>记录</Button></form></CardContent></Card></div><div className="space-y-2">{evals.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="break-words font-medium">{item.candidate_id} vs {item.baseline_id || 'baseline 未指定'}</div><div className="text-xs text-muted-foreground">{item.suite}</div></div><Badge className="self-start sm:self-auto">{item.verdict}</Badge></CardContent></Card>)}</div></TabsContent>
    <TabsContent value="promotions" className="space-y-4"><Card><CardHeader><CardTitle>提升 Generation</CardTitle><CardDescription>这是人工门控的下一次启动切换，不会安装日常可执行文件。</CardDescription></CardHeader><CardContent><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); if (window.confirm(`确认从 ${promotion.from} 提升到 ${promotion.to}？`)) void promote({ from_id: promotion.from, to_id: promotion.to, eval_id: promotion.evalId || undefined, actor: promotion.actor || 'human' }); }}><GenerationSelect label="From" value={promotion.from} onChange={(from) => setPromotion({ ...promotion, from })} generations={generations}/><GenerationSelect label="To" value={promotion.to} onChange={(to) => setPromotion({ ...promotion, to })} generations={generations}/><Field label="Eval ID（可选）"><Input value={promotion.evalId} onChange={(event) => setPromotion({ ...promotion, evalId: event.target.value })}/></Field><Field label="Actor"><Input value={promotion.actor} onChange={(event) => setPromotion({ ...promotion, actor: event.target.value })}/></Field><div className="md:col-span-2"><Button type="submit" disabled={busy || !promotion.from || !promotion.to}>确认提升</Button></div></form></CardContent></Card><div className="space-y-2">{promotions.map((item) => <Card key={item.id}><CardContent className="flex flex-col gap-2 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="break-words font-medium">{item.from_id} → {item.to_id}</div><div className="text-xs text-muted-foreground">{item.actor} · {item.applies_at}</div></div><Badge className="self-start sm:self-auto">{item.phase}</Badge></CardContent></Card>)}</div></TabsContent>
  </Tabs></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
function GenerationSelect({ label, value, onChange, generations, optional }: { label: string; value: string; onChange: (value: string) => void; generations: Array<{ id: string }>; optional?: boolean }) { return <Field label={label}><Select value={value || (optional ? '__none' : '')} onValueChange={(next) => onChange(next === '__none' ? '' : next)}><SelectTrigger><SelectValue placeholder="选择 Generation"/></SelectTrigger><SelectContent>{optional ? <SelectItem value="__none">不指定</SelectItem> : null}{generations.map((item) => <SelectItem key={item.id} value={item.id}>{item.id}</SelectItem>)}</SelectContent></Select></Field>; }
