// Package ui embeds the built Vite UI shell and serves it from the Go
// process (NFR: single binary plus UI assets). The dist directory is
// generated by `npm --prefix ui run build`; the committed .keep
// placeholder keeps go:embed compiling before the first build, in which
// case the handler reports the missing build instead of failing obscurely.
package ui

import (
	"embed"
	"errors"
	"io/fs"
	"net/http"
	"path"
	"strings"
)

//go:embed all:dist
var distFS embed.FS

// Handler serves the embedded UI build.
func Handler() http.Handler {
	sub, err := fs.Sub(distFS, "dist")
	if err != nil {
		// dist is embedded at compile time; Sub can only fail on a
		// broken build, which must not boot silently.
		panic("ui: embedded dist missing: " + err.Error())
	}
	return NewHandler(sub)
}

// NewHandler serves fsys as a single-page app: "/" and known files are
// served directly, everything else falls back to index.html so the UI's
// client-side state stays in charge. A missing index.html (dist not
// built) yields an actionable 503 instead of a bare 404.
func NewHandler(fsys fs.FS) http.Handler {
	files := http.FileServerFS(fsys)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			w.Header().Set("Allow", "GET, HEAD")
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		name := strings.TrimPrefix(path.Clean(r.URL.Path), "/")
		if name == "" {
			name = "index.html"
		}
		if _, err := fs.Stat(fsys, name); err != nil {
			if !errors.Is(err, fs.ErrNotExist) {
				http.Error(w, "ui unavailable", http.StatusInternalServerError)
				return
			}
			// Unknown path: SPA fallback to the app shell.
			name = "index.html"
		}
		if name == "index.html" {
			if _, err := fs.Stat(fsys, "index.html"); err != nil {
				w.Header().Set("Content-Type", "text/plain; charset=utf-8")
				w.WriteHeader(http.StatusServiceUnavailable)
				_, _ = w.Write([]byte("UI not built: run `npm --prefix ui ci && npm --prefix ui run build` and restart.\n"))
				return
			}
			http.ServeFileFS(w, r, fsys, "index.html")
			return
		}
		files.ServeHTTP(w, r)
	})
}
