import { TanStackRouterVite } from "@tanstack/router-plugin/vite";
import tailwindcss from "@tailwindcss/vite";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import tsConfigPaths from "vite-tsconfig-paths";
import { existsSync, readFileSync } from "fs";
import { resolve } from "path";
import { fileURLToPath } from "url";
import {
  UI_SDK_PACKAGE_NAME as UI_SDK_SOURCE_PACKAGE_NAME,
  UI_SDK_VERSION as UI_SDK_SOURCE_VERSION,
} from "../sdk/ui/src/index";

const UI_SDK_PACKAGE_NAME = UI_SDK_SOURCE_PACKAGE_NAME;
const UI_SDK_EXPECTED_VERSION = UI_SDK_SOURCE_VERSION;
const UI_SDK_PROVENANCE_MARKER = `${UI_SDK_PACKAGE_NAME}@${UI_SDK_EXPECTED_VERSION}`;
const UI_SDK_ROOT = fileURLToPath(new URL("../sdk/ui", import.meta.url));
const UI_SDK_PACKAGE_FILE = resolve(UI_SDK_ROOT, "package.json");
const DEFAULT_UI_ASSEMBLY_ENTRY = fileURLToPath(new URL("src/generated/assembly.ts", import.meta.url));
const UI_ASSEMBLY_ENTRY = resolve(process.env.VIVY_UI_ASSEMBLY_ENTRY?.trim() || DEFAULT_UI_ASSEMBLY_ENTRY);
const UI_ASSEMBLY_GENERATED_MARKER = "// Code generated by vivy-sdk. DO NOT EDIT.";
const UI_SDK_PACKAGE = JSON.parse(readFileSync(UI_SDK_PACKAGE_FILE, "utf8")) as {
  name?: unknown;
  version?: unknown;
};
if (UI_SDK_PACKAGE.name !== UI_SDK_PACKAGE_NAME || UI_SDK_PACKAGE.version !== UI_SDK_EXPECTED_VERSION) {
  throw new Error(`Vivy UI SDK package must pin ${UI_SDK_PACKAGE_NAME}@${UI_SDK_EXPECTED_VERSION}`);
}
if (!existsSync(UI_ASSEMBLY_ENTRY) || !readFileSync(UI_ASSEMBLY_ENTRY, "utf8").includes(UI_ASSEMBLY_GENERATED_MARKER)) {
  throw new Error("Vivy UI Assembly is missing its generated-code marker");
}

/** Sealed into the frontend build so its SDK contract is inspectable. */
export const UI_BUILD_PROVENANCE = Object.freeze({
  uiSdk: Object.freeze({
    packageName: UI_SDK_PACKAGE_NAME,
    version: UI_SDK_EXPECTED_VERSION,
  }),
});

const SOURCE_LOCATION_PLUGIN_CANDIDATES = [
  process.env.MEOO_SOURCE_LOCATION_PLUGIN_PATH,
  "/app/sdk/lib/src/plugins/source-location-babel.js",
  resolve(process.cwd(), "node_modules/@ali/oneday-agent-sdk/lib/src/plugins/source-location-babel.js"),
].filter(Boolean) as string[];

const SOURCE_LOCATION_PLUGIN_PATH = SOURCE_LOCATION_PLUGIN_CANDIDATES.find((path) => existsSync(path));

/**
 * React + Vite 构建配置
 *
 * 硬约束：
 * - dev server 必须监听 3015 + strictPort（沙箱只开放一个代理端口）
 * - outDir 'dist' / assetsDir 'assets' — 归一化产物目录
 */
export default defineConfig({
  define: {
    __VIVY_UI_BUILD_PROVENANCE__: JSON.stringify(UI_BUILD_PROVENANCE),
    __VIVY_UI_SDK_PACKAGE_NAME__: JSON.stringify(UI_BUILD_PROVENANCE.uiSdk.packageName),
    __VIVY_UI_SDK_VERSION__: JSON.stringify(UI_BUILD_PROVENANCE.uiSdk.version),
    __VIVY_UI_SDK_PROVENANCE_MARKER__: JSON.stringify(UI_SDK_PROVENANCE_MARKER),
  },
  resolve: {
    alias: {
      "@vivy/ui-sdk": resolve(UI_SDK_ROOT, "src"),
      "@vivy/ui-assembly": UI_ASSEMBLY_ENTRY,
      "@vivy/generated-assembly": UI_ASSEMBLY_ENTRY,
    },
  },
  plugins: [
    tailwindcss(),
    TanStackRouterVite(),
    viteReact({
      babel: {
        plugins: SOURCE_LOCATION_PLUGIN_PATH
          ? [[SOURCE_LOCATION_PLUGIN_PATH, { projectRoot: process.cwd() }]]
          : [],
      },
    }),
    tsConfigPaths(),
  ],
  server: {
    host: "0.0.0.0",
    port: 3015,
    strictPort: true,
    allowedHosts: true,
    // HMR 默认关闭：沙箱预览 iframe 下 HMR 的整页 reload 会放大任何 transform error
    // 如需热更，改为: hmr: { clientPort: 443, protocol: 'wss' }
    hmr: false,
    proxy: {
      "/rpc": {
        // VIVY_BACKEND_ADDR lets the Studio console point the dev server at
        // its managed headless backend's live port; the default matches the
        // standard split pair (just run at 127.0.0.1:8787).
        target: process.env.VIVY_BACKEND_ADDR || "http://127.0.0.1:8787",
        ws: true,
      },
    },
  },
  build: {
    outDir: "dist",
    assetsDir: "assets",
    emptyOutDir: true,
    rollupOptions: {
      output: {
        entryFileNames: "assets/[name]-[hash].js",
        chunkFileNames: "assets/[name]-[hash].js",
        assetFileNames: "assets/[name]-[hash][extname]",
      },
    },
  },
});
