// E2E workdir preparation: builds an isolated workdir for the real
// vivy.exe (fresh sqlite, mock provider, repo fixtures bundle). The
// workdir lives under ui/.e2e-workdir and is gitignored. Called from
// playwright.config.ts at config-load time, because Playwright starts
// the webServer before globalSetup would run.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const E2E_ADDR = "127.0.0.1:8799"; // never collides with the 8787 dev server

const here = path.dirname(fileURLToPath(import.meta.url)); // ui/e2e
const repoRoot = path.resolve(here, "..", "..");
export const e2eWorkdir = path.resolve(path.join(here, "..", ".e2e-workdir"));

export function prepareE2eWorkdir(): void {
  const workdir = e2eWorkdir;
  fs.rmSync(workdir, { recursive: true, force: true });
  fs.mkdirSync(path.join(workdir, "data"), { recursive: true });

  const bundleDir = path.join(repoRoot, "fixtures", "provider").replace(/\\/g, "/");
  const dbPath = path.join(workdir, "data", "vivy.db").replace(/\\/g, "/");
  const config = [
    "# Generated by ui/e2e/global-setup.ts for the Playwright smoke run.",
    "# Mock provider only; never point this at a real credential.",
    "server:",
    `  addr: "${E2E_ADDR}"`,
    "storage:",
    "  backend: sqlite",
    "  sqlite:",
    `    path: "${dbPath}"`,
    "providers:",
    "  active: openai",
    `  bundle_dir: "${bundleDir}"`,
    "  openai:",
    "    env_key: OPENAI_API_KEY",
    "    default_model: gpt-4o-mini",
    "  anthropic:",
    "    env_key: ANTHROPIC_API_KEY",
    "    default_model: claude-sonnet-4-5",
    "runtime:",
    "  mock: true",
    "  stream_buffer: 256",
    "  max_event_payload_bytes: 65536",
    "tools:",
    "  enabled:",
    "    - echo_info",
    "    - write_note",
    "  approval:",
    "    expiration: 5m",
    "",
  ].join("\n");
  fs.writeFileSync(path.join(workdir, "config.yaml"), config, "utf8");
}
